const makeActivity=(day,tool,mission,principle,steps,target,starter={})=>({day,tool,mission,principle,steps,target,starter});

const lessonActivities=[
  makeActivity(1,"synth","用同一个音做出三种明显不同的声音。","音高、时值、力度和音色是可以独立控制的四个维度。",["播放 C4","改变至少三个参数","用 A/B 对比两版"],{minTweaks:3,minPlays:3,minCompares:1}),
  makeActivity(2,"tour","按真实工作流依次找到迷你 DAW 的五个区域。","DAW 的核心路径是运输控制、轨道、编辑区、混音器和导出。",["点击运输区","找到轨道与编辑区","最后进入混音和导出"],{zones:["transport","tracks","editor","mixer","export"]}),
  makeActivity(3,"drums","建立四四拍的四个稳定大拍。","拍是稳定脉搏，小节把拍组织成可感知的循环。",["速度设为 90 BPM","在每个大拍放 Kick","播放并数 1-2-3-4"],{bpm:[88,92],kickAt:[0,4,8,12],minPlays:1},{bpm:90}),
  makeActivity(4,"piano","在钢琴卷帘中找齐 C 大调七个音名。","白键音名按 C-D-E-F-G-A-B 循环。",["依次放入 C 到 B","不要使用黑键音","播放音阶"],{minNotes:7,mustPitchClasses:[0,2,4,5,7,9,11],allowedPitchClasses:[0,2,4,5,7,9,11],minPlays:1}),
  makeActivity(5,"piano","写出半音、全音和八度三种距离。","半音是相邻键，全音等于两个半音，八度等于十二个半音。",["先放 C4","加入 C♯4、D4","最后加入 C5"],{intervals:[1,2,12],minNotes:4}),
  makeActivity(6,"piano","录入一条有强弱变化的 8 音 MIDI。","MIDI 的位置、长度和力度共同决定演奏感。",["写至少 8 个音","循环点击音符改变力度","播放检查强弱"],{minNotes:8,velocityVariation:true,minPlays:1}),
  makeActivity(7,"drums","把同一节奏改成 3/4 拍并选择合适速度。","速度决定时间密度，拍号决定重音分组。",["拍号设为 3/4","速度调到 70–100","每小节放三个大拍"],{timeSig:"3/4",bpm:[70,100],kickAt:[0,4,8],minPlays:1},{timeSig:"3/4",bpm:84}),
  makeActivity(8,"piano","修正一组故意偏离网格的音符。","量化是把演奏向网格靠近，而不是抹去全部感觉。",["播放偏移版","点击 80% 量化","保留一次轻微 Humanize"],{quantizeUsed:true,humanizeUsed:true,minPlays:1},{offGrid:true}),
  makeActivity(9,"arrange","用三种声部搭出一个四小节循环。","循环需要节奏、低音、和声或旋律分工，而不是无限堆层。",["加入节奏层","加入低音与旋律层","设置三档不同能量"],{minSections:3,maxSections:3,required:["节奏","低音","旋律"],energyChangesMin:2}),
  makeActivity(10,"arrange","完成一张 8 小节声音明信片。","短作品也需要开始、发展和收尾。",["建立开始段","加入发展段","用收尾段降低能量"],{minSections:4,required:["开始","发展","收尾"],peak:"发展",maxSections:6}),

  makeActivity(11,"drums","让 Kick、Snare、Hat、Perc 各承担一个角色。","基础鼓组由低频脉搏、骨架重音、时间细分和装饰组成。",["四轨各放至少一击","逐轨静音对比","播放完整鼓组"],{minKick:2,minSnare:2,minHat:4,minPerc:1,minPlays:1}),
  makeActivity(12,"drums","编出标准 2、4 拍 Backbeat。","许多流行律动的骨架是第 2、4 拍 Snare。",["Kick 放 1、3 拍","Snare 放 2、4 拍","Hat 放八分音符"],{kickAt:[0,8],snareAt:[4,12],hatAt:[0,2,4,6,8,10,12,14],minPlays:1}),
  makeActivity(13,"drums","对比八分与十六分 Hi-hat 的速度感。","细分密度改变推动感，但重音仍决定律动。",["先填满十六分 Hat","删成八分版本做比较","保存更适合的一版"],{minHat:8,maxHits:24,minCompares:1}),
  makeActivity(14,"drums","为十六分节奏设计可听见的重音循环。","相同位置的音符通过力度层级可以形成拍感。",["加入至少 8 个 Hat","把每拍第一下设为重音","播放检查四组强弱"],{minHat:8,accentMin:4,minPlays:1}),
  makeActivity(15,"drums","只用弱拍制造切分推动力。","切分来自预期强拍之外的重音或跨拍。",["保留稳定 Snare","在奇数格加入 Kick/Perc","确保至少四个反拍"],{snareAt:[4,12],offbeatMin:4,minPlays:1}),
  makeActivity(16,"drums","把直八分改成有弹性的 Swing。","Swing 是规律的一长一短，不是随机偏移。",["先听 50% 直拍","把 Swing 调到 58–66%","A/B 对比两版"],{swing:[58,66],minCompares:1,minPlays:2}),
  makeActivity(17,"drums","在主 Snare 之间加入轻 Ghost Note。","幽灵音连接重音，但力度必须明显低于主击。",["主 Snare 设为重音","加入至少两个轻 Snare","播放确认它不抢主拍"],{snareAt:[4,12],ghostMin:2,accentMin:2,minPlays:1}),
  makeActivity(18,"drums","根据目标风格完成一条 House 节奏。","风格由鼓角色的典型位置、密度和松紧共同决定。",["选择 House","Kick 放四踩","加入反拍 Hat 与 2/4 Clap"],{style:"House",kickAt:[0,4,8,12],snareAt:[4,12],offbeatMin:4}),
  makeActivity(19,"drums","做出低、中、高三档鼓组密度。","段落能量可以通过加法和减法控制。",["先写低密度骨架","复制为中密度","在最后四格做高密度 Fill"],{minHits:16,fillMin:3,densityVersions:3}),
  makeActivity(20,"drums","完成会呼吸的 8 小节鼓组缩略版。","稳定、变化、减法和回归构成完整鼓叙事。",["写稳定骨架","加入一次减法空拍","末尾加入 Fill 并播放"],{minKick:4,minSnare:2,minHat:8,restsMin:2,fillMin:3,minPlays:1}),

  makeActivity(21,"piano","只用 C 大调写一条 8 音旋律。","大调音阶提供统一材料，主音 C 是最稳定的落点。",["只用白键音阶","至少写 8 个音","最后回到 C"],{minNotes:8,allowedPitchClasses:[0,2,4,5,7,9,11],mustEndPitchClass:0,minPlays:1}),
  makeActivity(22,"piano","用 A 小调写出两种不同情绪。","关系大小调可共享音符，但主音重心不同。",["只用 A 自然小调","最后落在 A","保存强弱不同的两版"],{minNotes:8,allowedPitchClasses:[0,2,4,5,7,9,11],mustEndPitchClass:9,minCompares:1}),
  makeActivity(23,"piano","限制五个音写一个容易记住的 Hook。","五声音阶减少摩擦，让节奏和重复成为重点。",["只用 C D E G A","至少重复一个音型","播放并保留最短版本"],{minNotes:8,allowedPitchClasses:[0,2,4,7,9],motifRepeat:true,minPlays:1}),
  makeActivity(24,"piano","创作一个四音动机并重复。","动机是可辨认的最小音乐想法。",["前四步写动机","在后四步重复","只改变音区或力度"],{minNotes:8,motifRepeat:true,velocityVariation:true}),
  makeActivity(25,"piano","把同一动机做出三个单变量变体。","重复建立记忆，单变量变化保持身份。",["建立原动机","使用复制+变化功能","完成至少三次变化"],{variationUsed:true,variationCount:3,minNotes:12}),
  makeActivity(26,"piano","写出两小节问句和两小节答句。","问句悬而未决，答句回到稳定音。",["问句停在 G","答句回到 C","两句之间保留空拍"],{questionEnd:7,answerEnd:0,restsMin:1}),
  makeActivity(27,"piano","设计先上升后回落的旋律轮廓。","级进保持连贯，少量跳进制造重点。",["设置一个明确最高点","至少有一次五度以内跳进","最后反向回落"],{minRange:7,maxLeap:7,contour:"arch"}),
  makeActivity(28,"piano","通过删除音符让旋律呼吸。","休止决定分句、期待和下一次进入的力量。",["写一条 16 步旋律","保留至少四个空步","句尾留最长空白"],{minNotes:7,maxNotes:12,restsMin:4,endRest:true}),
  makeActivity(29,"piano","让强拍旋律落在 C 和弦音。","强拍和弦音稳定，弱拍经过音负责流动。",["强拍使用 C/E/G","弱拍可加入 D/F/A","播放检查稳定与流动"],{minNotes:8,strongPitchClasses:[0,4,7],strongRatio:.75,minPlays:1}),
  makeActivity(30,"piano","完成一条有动机、最高点和收尾的主题。","完整旋律把音阶、动机、轮廓和留白整合为一句话。",["至少写 12 个音","重复并发展动机","最后回主音并播放"],{minNotes:12,motifRepeat:true,minRange:7,mustEndPitchClass:0,minPlays:1}),

  makeActivity(31,"chords","从根音、三音、五音构建三个三和弦。","三和弦的根、三、五分别决定身份、色彩和支撑。",["加入 C、F、G","逐个试听","检查每个都是三和弦"],{minChords:3,mustInclude:["C","F","G"],minPlays:3}),
  makeActivity(32,"chords","在同一进行中对比大、小和弦。","大小和弦的关键差异是三音。",["至少加入一个大和弦","至少加入一个小和弦","A/B 播放两种色彩"],{minChords:4,majorMin:1,minorMin:1,minCompares:1}),
  makeActivity(33,"chords","只用 C 大调七个调内和弦搭进行。","调内和弦共享同一音阶材料。",["选择四个调内和弦","不要使用借用和弦","播放完整循环"],{minChords:4,diatonicOnly:true,minPlays:1}),
  makeActivity(34,"chords","完成 I–IV–V–I 功能进行。","主、前属、属、主构成最清晰的离开与回归。",["依次放 C、F、G、C","试听 G 的张力","确认最后 C 的落地"],{exact:["C","F","G","C"],minPlays:1}),
  makeActivity(35,"chords","搭建 I–V–vi–IV 并改变和声节奏。","相同和弦通过节奏、转位和音色仍能获得个性。",["依次放 C G Am F","播放原版","改变一次和弦时值"],{exact:["C","G","Am","F"],rhythmChanged:true,minPlays:2}),
  makeActivity(36,"chords","用转位让相邻声部少移动。","共同音保留和最近距离移动能让和声更顺。",["建立四和弦循环","至少设置两个转位","播放最高声部线"],{minChords:4,inversionsMin:2,minPlays:1}),
  makeActivity(37,"chords","用七和弦增加两处色彩。","七音增加张力与连接，但不必每个和弦都使用。",["选择四个和弦","至少两个开启七音","比较三和弦版"],{minChords:4,seventhMin:2,minCompares:1}),
  makeActivity(38,"chords","在大调进行中加入一次 iv 小和弦。","借用和弦通过单个调外音制造鲜明颜色。",["先放 F","接着放 Fm","最后回 C"],{containsSequence:["F","Fm","C"],borrowedMin:1,minPlays:1}),
  makeActivity(39,"chords","为固定旋律目标音选择四个兼容和弦。","配和弦先保护长音与强拍，再考虑功能方向。",["启用旋律目标提示","每格选包含目标音的和弦","兼容率达到 75%"],{minChords:4,compatibility:.75,targetMelody:true}),
  makeActivity(40,"chords","完成 8 格旋律和声 Demo。","旋律与和声都要有独立方向，合起来又互相支持。",["使用至少 8 个和弦格","加入转位和七和弦","播放并保存完整 Demo"],{minChords:8,inversionsMin:2,seventhMin:1,minPlays:1}),

  makeActivity(41,"arrange","把循环扩展成四个有职责的段落。","曲式管理熟悉、变化和期待。",["加入前奏、主歌、副歌、尾奏","设置能量差","播放结构缩略图"],{minSections:4,required:["前奏","主歌","副歌","尾奏"],energyChangesMin:2}),
  makeActivity(42,"arrange","设计不泄露全部素材的前奏。","前奏只需建立世界、给线索并提示进入。",["前奏能量不高于 4","长度不超过 8 小节","后面接主歌"],{required:["前奏","主歌"],introMax:4,maxBarsForIntro:8}),
  makeActivity(43,"arrange","做出两个相似但不同的主歌。","第二主歌应保留身份，同时回应故事已经发展。",["放入两个主歌","保持主歌 2 能量接近","加入一次变化标记"],{counts:{"主歌":2},variation:true,verseEnergyGapMax:2}),
  makeActivity(44,"arrange","用预副歌连续蓄力进入副歌。","上升线、加密或减法都能制造期待。",["安排主歌→预副歌→副歌","预副歌能量上升","副歌明显高于主歌"],{containsSequence:["主歌","预副歌","副歌"],ascendingInto:"副歌",chorusHigher:true}),
  makeActivity(45,"arrange","让副歌成为唯一能量峰值。","副歌兑现期待，峰值来自聚焦与对比。",["至少有一个主歌","加入副歌","把副歌设为全曲最高能量"],{required:["主歌","副歌"],peak:"副歌",chorusHigher:true}),
  makeActivity(46,"arrange","插入桥段并自然回到最终副歌。","桥段打开新视角，但要保留回归主材料的需求。",["安排副歌→桥段→副歌","桥段能量与前段不同","最终副歌重新升高"],{containsSequence:["副歌","桥段","副歌"],variation:true,finalChorusPeak:true}),
  makeActivity(47,"arrange","为重复副歌设计两次升级。","宏观相同、微观不同能让回归既熟悉又新鲜。",["加入三个副歌","每次能量逐步提升","至少一个副歌标记变化"],{counts:{"副歌":3},ascendingCopies:"副歌",variation:true}),
  makeActivity(48,"arrange","画出有低谷和峰值的全曲能量线。","持续最大会让耳朵适应，峰值前的低谷很重要。",["至少六个段落","能量不能只升不降","设置唯一 10/10 峰值"],{minSections:6,energyChangesMin:4,hasValley:true,peakValue:10}),
  makeActivity(49,"arrange","在参考曲时间轴上标记五个结构事件。","拆歌要提取段落长度、进入退出和能量决策。",["启用参考分析","添加至少五个段落标记","记录一次进入和一次退出"],{referenceAnalyzed:true,minSections:5,entryExitMarked:true}),
  makeActivity(50,"arrange","完成可从头播放的完整曲式蓝图。","蓝图优先解决段落职责与比例，而不是音色细节。",["至少八个段落","包含主歌、副歌和桥段","保存蓝图版本"],{minSections:8,required:["主歌","副歌","桥段"],blueprintSaved:true}),

  makeActivity(51,"synth","为主角、配角和背景各做一个音色。","音色选择应回答角色、频段和前后位置。",["保存三个音色快照","每个快照参数不同","逐个试听角色差异"],{snapshotsMin:3,minTweaks:4,minPlays:3}),
  makeActivity(52,"synth","不加效果地比较四种基础波形。","波形的谐波结构决定基础明暗与质感。",["试听 Sine、Triangle、Square、Saw","保持音高一致","完成四波形对比"],{wavesPlayed:["sine","triangle","square","sawtooth"]}),
  makeActivity(53,"synth","用 ADSR 做出 Pluck 与 Pad 两个预设。","包络决定声音随时间的形状。",["Pluck 使用短起音短尾音","Pad 使用长起音长尾音","保存两个快照"],{snapshotsMin:2,envelopeContrast:true,minPlays:2}),
  makeActivity(54,"synth","用滤波器完成一次从暗到亮的扫频。","截止频率决定明暗，共振强调截止点。",["亮度先低后高","共振保持不过量","录入一次自动化"],{brightnessSweep:true,automationMin:1,minPlays:1}),
  makeActivity(55,"synth","让 LFO 分别调制音量和滤波。","LFO 用规律周期运动赋予持续音生命力。",["设置同步速率","试听音量调制","再试听滤波调制"],{lfoTargets:["volume","filter"],minCompares:1}),
  makeActivity(56,"synth","把一个短采样切成四片重新排列。","采样可通过切片、移调和反向变成新材料。",["建立四个切片","至少移动一个切片","使用一次反向或移调"],{slicesMin:4,sliceMovesMin:1,reverseOrPitch:true}),
  makeActivity(57,"synth","用三层互补音色构建一个复合声音。","分层要按频段、瞬态或宽度互补。",["加入 Sub、Body、Attack","逐层静音检查职责","保存三层预设"],{layers:["Sub","Body","Attack"],snapshotsMin:1,minPlays:1}),
  makeActivity(58,"synth","制作一条小音箱也能听见的 Bass。","Sub 提供重量，适量谐波提供可辨识度。",["音高降到低音区","加入中等亮度谐波","在小音箱模式试听"],{pitchMax:48,brightness:[4,8],smallSpeakerTest:true,minPlays:1}),
  makeActivity(59,"synth","用短空间和长空间做出前后层次。","空间效果安排距离、大小和时间。",["保存短 Room","保存长 Hall","A/B 比较前后位置"],{spaces:["Room","Hall"],snapshotsMin:2,minCompares:1}),
  makeActivity(60,"synth","建立六类统一音色板。","音色板通过共享质感和空间让作品像同一个世界。",["保存六个角色快照","至少使用三种波形","命名并冻结音色板"],{snapshotsMin:6,uniqueWavesMin:3,paletteNamed:true}),

  makeActivity(61,"mix","只保留一个主角并降低竞争声部。","编曲本质是在每个时刻分配注意力。",["选择主角轨","降低两个竞争轨","试听焦点是否清楚"],{leadSelected:true,loweredChannelsMin:2,minPlays:1}),
  makeActivity(62,"mix","让 Kick 与 Bass 在时间和音量上分工。","低频冲突优先用选音、时序与包络解决。",["Solo Kick+Bass","调整两轨音量差","设置一次低频让位"],{soloPair:true,volumeEditsMin:2,sidechain:true}),
  makeActivity(63,"mix","把三个中频和声声部排到不同位置。","音区、节奏和声部数量比堆 EQ 更能解决拥挤。",["选择三个 Music 声部","设置不同声像或音量","单声道检查一次"],{activeChannelsMin:3,panSpread:true,mono:true}),
  makeActivity(64,"mix","用高频层设计主歌到副歌的明暗变化。","高频是段落奖励，不应从头持续铺满。",["主歌降低高频层","副歌提高高频层","A/B 比较两段"],{sectionMixesMin:2,brightnessContrast:true,minCompares:1}),
  makeActivity(65,"mix","为四条轨分配主角、配角和背景角色。","角色是动态的，乐器可以随段落改变前后位置。",["指定一个 Lead","至少一个 Support","至少一个 Background"],{roles:["Lead","Support","Background"],roleAssignmentsMin:4}),
  makeActivity(66,"piano","让低音与主旋律形成一次反向运动。","横向声部自然比垂直和弦正确更重要。",["写一条上行主旋律","加入下行低音","播放检查两线独立"],{twoVoices:true,contraryMotion:true,minPlays:1}),
  makeActivity(67,"piano","只在主旋律空隙加入两个 Fill。","填充句应回应空白并提示转场。",["主旋律保留空拍","在两个空拍加入高音 Fill","最后一格做转场"],{restsMin:2,fillsInRests:2,endFill:true}),
  makeActivity(68,"mix","为音量、滤波和空间各画一条自动化。","自动化是随时间塑造进入、增长和消失。",["添加音量曲线","添加亮度曲线","添加空间发送曲线"],{automationTypes:["volume","filter","space"]}),
  makeActivity(69,"mix","通过 Mute Test 删除至少两条无效层。","删掉重复职责能让真正重要的元素获得空间。",["逐轨执行静音对比","永久关闭两条低贡献轨","匹配音量后再比较"],{muteTestsMin:4,mutedChannelsMin:2,levelMatched:true}),
  makeActivity(70,"arrange","完成从头到尾没有空白决策的编曲 V1。","编曲 V1 先保证结构、角色、低频和转场完整。",["至少八个完整段落","标记所有主角","保存编曲 V1"],{minSections:8,required:["主歌","副歌"],rolesMarked:true,blueprintSaved:true}),

  makeActivity(71,"record","把最大输入峰值控制在安全区域。","录音要足够清楚并保留余量，削波无法真正恢复。",["启动测试信号","调节输入增益","峰值保持 -12 到 -6 dBFS"],{recordTest:true,gain:[42,68],safePeak:true}),
  makeActivity(72,"record","在三个模拟位置中选出反射最少的一处。","家庭录音先优化位置，再考虑后期修复。",["测试三个麦克风距离","降低房间反射","保存最佳位置"],{positionTestsMin:3,roomMax:4,bestPositionSaved:true}),
  makeActivity(73,"record","建立稳定的人声录音设置。","麦距、角度、监听和演唱准备共同决定素材质量。",["麦距设在 10–20 cm","监听保持舒适","完成一次正式测试"],{distance:[10,20],monitor:[35,70],recordTest:true}),
  makeActivity(74,"record","录三条 Take 并完成一次 Comp。","先选整体情绪，再替换真正影响听感的句子。",["录制至少三条 Take","选择主 Take","用一个片段完成 Comp"],{takesMin:3,comp:true,compEditsMin:1}),
  makeActivity(75,"record","降低噪声但保留自然呼吸。","编辑应消除干扰，而不是消除生命感。",["处理两处噪声","呼吸最多降低不过度删除","启用淡化"],{cleanupMin:2,breathRange:[20,70],fades:true}),
  makeActivity(76,"record","只修正真正破坏 Groove 的节奏偏差。","节奏编辑要保留有意的 Swing 与拖后。",["标记三处偏差","修正量保持温和","A/B 对比自然度"],{timingEditsMin:3,timing:[20,65],minCompares:1}),
  makeActivity(77,"record","完成自然音高校正而不抹平滑音。","音高校正先解决刺耳偏差，再保护表达路径。",["设置正确调性","校正量保持 20–60%","保存自然版与效果版"],{pitch:[20,60],snapshotsMin:2,keySelected:true}),
  makeActivity(78,"record","比较三个真实乐器拾音位置。","声源位置移动几厘米就可能比 EQ 更有效。",["保存三个位置测试","选择主版本","完成一次独立双轨"],{positionTestsMin:3,bestPositionSaved:true,doubleTracked:true}),
  makeActivity(79,"record","把工程整理成别人五分钟能看懂的结构。","清晰命名、颜色、分组和版本号比记忆可靠。",["命名四类轨道","建立分组","保存带版本号工程"],{named:true,groupsMin:4,versioned:true}),
  makeActivity(80,"record","导出并验证一套可混音素材。","所有 Stem 必须同起点、无削波、版本明确。",["导出 Dry 与 FX 版本","生成至少五个 Stem","执行一次空工程验证"],{exportsMin:2,stemsMin:5,verified:true}),

  makeActivity(81,"mix","关闭插件，只用音量建立平衡。","混音首先是稳定焦点与比例。",["移动至少四个推子","主输出保留余量","小音量播放一次"],{volumeEditsMin:4,headroom:true,quietCheck:true,minPlays:1}),
  makeActivity(82,"mix","建立有中心、有两侧的声像图。","宽度必须兼顾中心稳定与单声道兼容。",["低频保持中心","两条音乐轨分到左右","完成单声道检查"],{bassCentered:true,panSpread:true,mono:true}),
  makeActivity(83,"mix","只为三个明确问题添加 EQ。","EQ 先解决问题，再考虑美化。",["为三轨各做一次 EQ","每次标注问题频段","匹配音量 A/B"],{eqEditsMin:3,eqReasons:true,levelMatched:true}),
  makeActivity(84,"mix","用压缩控制峰值并保留冲击。","Attack 与 Release 决定瞬态和回弹。",["设置一次慢 Attack","增益衰减控制在 1–4 dB","匹配输出响度"],{compressionEditsMin:2,gainReduction:[1,4],levelMatched:true}),
  makeActivity(85,"mix","改善一条轨的瞬态而不增加刺耳。","瞬态决定冲击和节奏轮廓。",["选择一条鼓轨","调整 Attack 与 Sustain","小音量 A/B"],{transientEditsMin:2,quietCheck:true,minCompares:1}),
  makeActivity(86,"mix","用短、长两个混响建立前后层次。","Pre-delay、Decay 和发送量共同塑造距离。",["建立短 Room","建立长 Hall","让前景比背景更干"],{reverbTypes:["Room","Hall"],depthOrder:true}),
  makeActivity(87,"mix","只在两个句尾使用 Delay Throw。","延迟应填空而不是遮住下一句。",["选择同步拍点","添加两个 Throw","确保下一句前结束"],{delayThrowsMin:2,delaySynced:true,clearNextPhrase:true}),
  makeActivity(88,"mix","建立五个功能总线并检查路由。","总线用于集中控制同类职责，而不是增加复杂度。",["创建 Drums/Bass/Music/Vocal/FX","检查无重复输出","轻度处理一个总线"],{buses:["Drums","Bass","Music","Vocal","FX"],routingClean:true,busProcessing:true}),
  makeActivity(89,"mix","与参考曲匹配响度并完成三设备检查。","参考曲提供比例尺度，多设备测试检查翻译性。",["导入参考并匹配响度","启用手机与单声道模式","记录三项差异"],{reference:true,levelMatched:true,deviceChecksMin:3}),
  makeActivity(90,"mix","输出一版通过技术检查的全曲混音 V1。","混音 V1 应具备平衡、低频、层次、空间和合理动态。",["完成至少十项混音操作","检查峰值与尾音","导出 WAV 与 MP3"],{editsMin:10,headroom:true,tailChecked:true,formats:["WAV","MP3"]}),

  makeActivity(91,"finish","定义什么问题会阻止这首歌完成。","完成意味着核心意图清楚，剩余修改收益已很低。",["写下三个核心意图","把问题分三级","设置冻结日期"],{coreIntentMin:3,priorityMin:3,freezeDate:true}),
  makeActivity(92,"finish","把三位听者反馈拆成感受、问题和建议。","听者体验最可靠，具体解决方案由创作者决定。",["录入三条反馈","完成三层分类","标出重复问题"],{feedbackMin:3,feedbackLayers:true,repeatedIssue:true}),
  makeActivity(93,"finish","只处理结构层的三个修改。","结构修改影响最大，应早于编曲和混音细修。",["选择三个结构问题","完成删减或调序","冻结最终结构"],{structureMin:3,structureFrozen:true}),
  makeActivity(94,"finish","只处理角色、对比和声部职责。","编曲修改优先解决遮挡和重复职责。",["选择三个编曲问题","完成至少三次修改","冻结最终编曲"],{arrangementMin:3,arrangementFrozen:true}),
  makeActivity(95,"finish","按优先级完成最后五项混音修改。","最终混音应验证问题、动作和听感结果。",["添加五项混音修正","逐项 A/B","冻结候选版本"],{mixMin:5,abChecksMin:3,mixFrozen:true}),
  makeActivity(96,"finish","做一条克制、可解释的母带链。","母带是整体质量控制，不是拯救混音。",["母带处理不超过四个模块","限制器不过度工作","与 Pre-master 匹配响度"],{masterModules:[1,4],limitingMax:4,levelMatched:true}),
  makeActivity(97,"finish","选择兼顾响度与动态的导出设置。","流媒体归一化不会奖励过度压扁的动态。",["目标响度设在合理范围","True Peak 留余量","选择 24-bit WAV"],{lufs:[-16,-9],truePeakMax:-1,format:"24-bit WAV"}),
  makeActivity(98,"finish","完成标题、封面和作品说明。","视觉与文字应延续音乐核心情绪。",["填写作品标题","完成封面状态","写 50–100 字说明"],{title:true,cover:true,description:true}),
  makeActivity(99,"finish","完成版权、元数据、试听和备份清单。","发布前检查把风险变成可执行确认。",["确认版权与元数据","完成三设备试听","建立两份备份"],{metadata:true,copyright:true,deviceChecksMin:3,backupMin:2}),
  makeActivity(100,"finish","发布第一首完整作品并写毕业复盘。","完成一个创作循环，是进入下一首作品的起点。",["完成最终导出","标记已发布或已分享","写下三项复盘与下一目标"],{finalExport:true,published:true,reflectionMin:3,nextGoal:true})
];
