const StudioAudio=(()=>{
  const sampleRate=22050;
  let activeAudio=null,activeUrl=null;
  const clamp=(value,min,max)=>Math.max(min,Math.min(max,value));
  const wave=(phase,type)=>type==="square"?(Math.sin(phase)>=0?1:-1):type==="triangle"?2/Math.PI*Math.asin(Math.sin(phase)):type==="sawtooth"?2*((phase/(Math.PI*2))%1)-1:Math.sin(phase);
  const midi=note=>440*Math.pow(2,(note-69)/12);
  const chordMidi={C:[48,52,55],Dm:[50,53,57],Em:[52,55,59],F:[53,57,60],G:[55,59,62],Am:[57,60,64],Bdim:[59,62,65],Fm:[53,56,60],Bb:[58,62,65]};

  function wavBlob(samples){
    const buffer=new ArrayBuffer(44+samples.length*2),view=new DataView(buffer);
    const text=(offset,value)=>{for(let i=0;i<value.length;i++)view.setUint8(offset+i,value.charCodeAt(i))};
    text(0,"RIFF");view.setUint32(4,36+samples.length*2,true);text(8,"WAVE");text(12,"fmt ");view.setUint32(16,16,true);view.setUint16(20,1,true);view.setUint16(22,1,true);view.setUint32(24,sampleRate,true);view.setUint32(28,sampleRate*2,true);view.setUint16(32,2,true);view.setUint16(34,16,true);text(36,"data");view.setUint32(40,samples.length*2,true);
    samples.forEach((sample,index)=>view.setInt16(44+index*2,clamp(sample,-1,1)*32767,true));
    return new Blob([buffer],{type:"audio/wav"});
  }

  function render(project){
    const bpm=clamp(Number(project.bpm)||90,45,180),sixteenth=60/bpm/4;
    const baseDuration=project.arrange?.sections?.length?Math.min(9,Math.max(4,project.arrange.sections.length*.72)):Math.max(4,16*sixteenth*2+.4);
    const samples=new Float32Array(Math.floor(baseDuration*sampleRate));
    const synthSettings=project.synth||{},brightnessAutomation=(synthSettings.automation||[]).filter(point=>point&&point.type==="brightness").map(point=>Number(point.value));
    const addTone=(start,duration,frequency,level=.16,type="sine",attack=.015,release=.08)=>{
      const first=Math.max(0,Math.floor(start*sampleRate)),last=Math.min(samples.length,Math.ceil((start+duration)*sampleRate));
      for(let i=first;i<last;i++){
        const t=i/sampleRate-start;
        const env=Math.min(1,t/Math.max(.005,attack),Math.max(0,(duration-t)/Math.max(.02,release)));
        const lfo=Math.sin(t*Math.max(.2,Number(synthSettings.lfoRate)||2)*Math.PI*2),target=synthSettings.lfoTarget;
        const modFrequency=frequency*(target==="pitch"?1+lfo*.018:1),modLevel=target==="volume"?.64+lfo*.32:1;
        const position=clamp(t/Math.max(.01,duration),0,1),automationIndex=position*Math.max(0,brightnessAutomation.length-1),left=Math.floor(automationIndex),right=Math.min(brightnessAutomation.length-1,left+1),blend=automationIndex-left;
        const automatedBrightness=brightnessAutomation.length>=2?brightnessAutomation[left]*(1-blend)+brightnessAutomation[right]*blend:Number(synthSettings.brightness)||5;
        const movingBrightness=clamp(automatedBrightness+(target==="filter"?lfo*3:0),1,10),harmonics=movingBrightness>3?Math.min(5,Math.ceil(movingBrightness/2)):1;
        let value=0;
        for(let h=1;h<=harmonics;h++)value+=wave(t*modFrequency*h*Math.PI*2,type)/(h*h*.7);
        if(synthSettings.resonance)value+=Math.sin(t*modFrequency*2*Math.PI*2)*(Number(synthSettings.resonance)/10)*.18;
        samples[i]+=value*env*level*modLevel;
      }
    };
    const addKick=start=>{
      const duration=.22,first=Math.floor(start*sampleRate),last=Math.min(samples.length,Math.ceil((start+duration)*sampleRate));
      for(let i=first;i<last;i++){const t=i/sampleRate-start,f=120*Math.pow(48/120,t/duration),env=Math.pow(1-t/duration,3);samples[i]+=Math.sin(t*f*Math.PI*2)*env*.52}
    };
    const addNoise=(start,duration,level)=>{
      const first=Math.floor(start*sampleRate),last=Math.min(samples.length,Math.ceil((start+duration)*sampleRate));
      for(let i=first;i<last;i++){const t=i/sampleRate-start,noise=Math.sin(i*12.9898)*43758.5453%1;samples[i]+=(noise*2-1)*Math.pow(1-t/duration,3)*level}
    };
    const drum=project.drums||{};
    for(let loop=0;loop<2;loop++){
      ["kick","snare","hat","perc"].forEach(role=>(drum[role]||[]).forEach((velocity,step)=>{
        if(!velocity)return;
        const swing=step%2?((Number(drum.swing)||50)-50)/100*sixteenth:0;
        const start=(loop*16+step)*sixteenth+swing+.04;
        if(role==="kick")addKick(start);else if(role==="snare")addNoise(start,.16,.32*velocity);else if(role==="hat")addNoise(start,.07,.15*velocity);else addTone(start,.12,620,.11*velocity,"triangle");
      }));
    }
    const synth=project.synth||{};
    const attack=.01+(Number(synth.attack)||1)/10*.28,release=.05+(Number(synth.release)||4)/10*.55;
    (project.piano?.notes||[]).forEach(note=>{
      for(let loop=0;loop<2;loop++)addTone((loop*16+note.step)*sixteenth+.04,sixteenth*.85,midi(note.pitch),.2*(note.velocity||.7),synth.wave||"triangle",attack,release);
    });
    (project.chords?.sequence||[]).forEach((item,index)=>{
      const notes=chordMidi[item.id]||chordMidi.C;
      const start=index*(baseDuration/Math.max(1,project.chords.sequence.length));
      notes.forEach((note,n)=>addTone(start+.03,Math.min(1.35,baseDuration/project.chords.sequence.length*.85),midi(note+(item.inversion?12*(n<item.inversion?1:0):0)),.07,synth.wave||"sine",.04,.3));
      if(item.seventh)addTone(start+.03,1.1,midi(notes[0]+10),.045,"sine",.04,.3);
    });
    if(!(project.piano?.notes||[]).length&&!(project.chords?.sequence||[]).length&&!(drum.kick||[]).some(Boolean)){
      const pitch=(Number(synth.pitch)||60)+(synth.pitchShift?5:0),baseMotif=synth.slices>=4?(synth.sliceOrder||[1,2,3,4]).flatMap(id=>[(id-1)*2,(id-1)*2]):[0,2,4,7,4,2,0],motif=synth.reverse?[...baseMotif].reverse():baseMotif;
      motif.slice(0,8).forEach((offset,index)=>{const start=index*.46;addTone(start,.38,midi(pitch+offset),.2,synth.wave||"sine",attack,release);if(synth.layers?.includes("Sub"))addTone(start,.38,midi(pitch+offset-12),.09,"sine",attack,release);if(synth.layers?.includes("Attack"))addTone(start,.08,midi(pitch+offset+12),.07,"square",.005,.025)});
    }
    if(project.arrange?.sections?.length){
      project.arrange.sections.forEach((section,index)=>{
        const start=index*.72,energy=(section.energy||5)/10;
        addKick(start+.02);addTone(start+.05,.62,midi(48+[0,9,5,7][index%4]),.08+energy*.08,"triangle",.02,.18);
        if(energy>6)addNoise(start+.36,.08,.14);
      });
    }
    const recording=project.record||{};
    if(recording.recordTest||recording.positionTests||recording.takes){
      const gain=clamp((Number(recording.gain)||50)/55,.25,1.45),distanceDamping=clamp(1-(Number(recording.distance)||15)/130,.45,1),roomAmount=clamp((Number(recording.room)||0)/10,0,.8),roomSamples=Math.floor(sampleRate*.11);
      let lowPass=0;for(let i=0;i<samples.length;i++){let current=samples[i]*gain;lowPass+=distanceDamping*(current-lowPass);current=lowPass;if(i>=roomSamples)current+=samples[i-roomSamples]*roomAmount*.32;samples[i]=current}
    }
    const mixer=project.mix||{},channels=mixer.channels||[],active=channels.filter(channel=>!channel.mute);
    if(channels.length){
      const average=(key)=>active.length?active.reduce((sum,channel)=>sum+(Number(channel[key])||0),0)/active.length:0;
      const volumeGain=active.length?clamp(average("volume")/68,.15,1.35)*(active.length/channels.length):0;
      const eqAmount=average("eq")/10,compression=average("comp")/10,reverb=average("reverb")/10,delay=average("delay")/10,transient=average("transient")/10;
      const roomDelay=Math.floor(sampleRate*(project.synth?.space==="Hall"?.19:.075));
      const tempoDelay=Math.floor(sampleRate*(60/bpm/2));
      let previous=0;
      for(let i=0;i<samples.length;i++){
        let current=samples[i];
        const bright=current-previous;previous=current;
        current+=bright*eqAmount*.7;
        if(i>=roomDelay)current+=samples[i-roomDelay]*(reverb*.28+(project.synth?.space==="Hall"?.08:0));
        if(i>=tempoDelay)current+=samples[i-tempoDelay]*delay*.25;
        current*=volumeGain*(1+transient*.12);
        if(compression>0)current=Math.tanh(current*(1+compression*2))/(1+compression*.35);
        samples[i]=current;
      }
    }
    if(project.synth?.smallSpeaker){
      let low=0;for(let i=0;i<samples.length;i++){low+=.025*(samples[i]-low);samples[i]=(samples[i]-low)*1.35}
    }
    if(project.finish?.masterModules){
      const drive=1+Math.min(4,project.finish.masterModules)*.13;
      for(let i=0;i<samples.length;i++)samples[i]=Math.tanh(samples[i]*drive);
    }
    let peak=.001;for(const sample of samples)peak=Math.max(peak,Math.abs(sample));
    const scale=Math.min(1,.88/peak);for(let i=0;i<samples.length;i++)samples[i]=Math.tanh(samples[i]*scale*1.05);
    return wavBlob(samples);
  }

  function attach(audio,blob){if(activeUrl)URL.revokeObjectURL(activeUrl);activeUrl=URL.createObjectURL(blob);audio.src=activeUrl;audio.load();return activeUrl}
  function play(audio,project){const blob=render(project);attach(audio,blob);activeAudio=audio;const result=audio.play();return {blob,promise:result}}
  function stop(){if(activeAudio){activeAudio.pause();activeAudio.currentTime=0}activeAudio=null}
  return {render,attach,play,stop,chordMidi};
})();

const ProjectStore=(()=>{
  const DB="hundred-day-composer",STORE="works";
  const open=()=>new Promise((resolve,reject)=>{
    if(!window.indexedDB){resolve(null);return}
    const request=indexedDB.open(DB,1);
    request.onupgradeneeded=()=>{if(!request.result.objectStoreNames.contains(STORE))request.result.createObjectStore(STORE,{keyPath:"id"})};
    request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error);
  });
  async function save(record){
    try{const db=await open();if(!db)throw new Error("no-indexeddb");await new Promise((resolve,reject)=>{const tx=db.transaction(STORE,"readwrite");tx.objectStore(STORE).put(record);tx.oncomplete=resolve;tx.onerror=()=>reject(tx.error)});return record}
    catch(_){let records=[];try{records=JSON.parse(localStorage.getItem("composer-saved-works")||"[]")}catch(__){records=[]}records.unshift({...record,wav:null});localStorage.setItem("composer-saved-works",JSON.stringify(records.slice(0,20)));return record}
  }
  async function list(){
    try{const db=await open();if(!db)throw new Error("no-indexeddb");const records=await new Promise((resolve,reject)=>{const request=db.transaction(STORE).objectStore(STORE).getAll();request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)});return records.sort((a,b)=>b.createdAt-a.createdAt)}
    catch(_){try{return JSON.parse(localStorage.getItem("composer-saved-works")||"[]")}catch(__){return []}}
  }
  const saveDraft=(day,project)=>localStorage.setItem(`composer-daw-draft-${day}`,JSON.stringify(project));
  const loadDraft=day=>{try{return JSON.parse(localStorage.getItem(`composer-daw-draft-${day}`)||"null")}catch(_){return null}};
  return {save,list,saveDraft,loadDraft};
})();

const ComposerStudio=(()=>{
  let root=null,activity=null,state=null,activeKit=null,onChange=()=>{},auditionTimer=null;
  const roles=["kick","snare","hat","perc"];
  const roleLabels={kick:"Kick",snare:"Snare",hat:"Hi-hat",perc:"Perc"};
  const pianoPitches=Array.from({length:13},(_,i)=>72-i);
  const noteNames=["C","C♯","D","E♭","E","F","F♯","G","A♭","A","B♭","B"];
  const sectionNames=["前奏","主歌","预副歌","副歌","桥段","尾奏","节奏","低音","旋律","开始","发展","收尾"];
  const chordNames=["C","Dm","Em","F","G","Am","Bdim","Fm","Bb"];
  const targetHas=(...keys)=>keys.some(key=>Object.prototype.hasOwnProperty.call(activity.target,key));

  function defaults(day,starter={}){
    return {
      version:3,day,bpm:starter.bpm||90,timeSig:starter.timeSig||"4/4",tour:{zones:[]},workbench:{materials:[],manualEdits:0},
      synth:{wave:"sine",pitch:60,attack:2,release:4,brightness:5,resonance:2,lfoRate:2,lfoTarget:"filter",lfoTargetsPlayed:[],space:"Room",tweaks:0,plays:0,compares:0,abSlots:{A:null,B:null,active:"LIVE"},snapshots:[],wavesPlayed:[],automation:[],layers:[],slices:0,sliceMoves:0,sliceOrder:[1,2,3,4],reverse:false,pitchShift:false,smallSpeaker:false,paletteName:""},
      drums:{kick:Array(16).fill(0),snare:Array(16).fill(0),hat:Array(16).fill(0),perc:Array(16).fill(0),swing:50,style:"Pop",plays:0,compares:0,densityVersions:0},
      piano:{notes:[],plays:0,compares:0,quantizeUsed:false,humanizeUsed:false,variationUsed:false,variationCount:0,twoVoices:false,endFill:false,targetMelody:false},
      chords:{sequence:[],inversion:0,seventh:false,plays:0,compares:0,rhythmChanged:false,targetMelody:false},
      arrange:{sections:[],selected:-1,variation:false,referenceAnalyzed:false,entryExitMarked:false,blueprintSaved:false,rolesMarked:false},
      record:{gain:50,distance:15,room:5,monitor:50,takes:0,comp:false,compEdits:0,cleanup:0,breath:50,fades:false,timing:40,timingEdits:0,pitch:35,keySelected:false,positionTests:0,bestPositionSaved:false,doubleTracked:false,named:false,groups:0,versioned:false,exports:0,stems:0,verified:false,recordTest:false,snapshots:0},
      mix:{channels:["Drums","Bass","Music","Vocal","FX"].map(name=>({name,volume:name==="Vocal"?78:65,pan:50,mute:false,role:"Support",eq:0,comp:0,reverb:0,delay:0,transient:0})),selected:0,plays:0,compares:0,edits:0,mono:false,reference:false,levelMatched:false,quietCheck:false,headroom:false,sidechain:false,soloPair:false,buses:[],routingClean:false,busProcessing:false,sectionMixes:0,brightnessContrast:false,automation:[],muteTests:0,deviceChecks:0,tailChecked:false,formats:[],rolesMarked:false},
      finish:{coreIntent:[],priorities:[],freezeDate:"",feedback:[],feedbackLayers:false,repeatedIssue:false,structure:0,structureFrozen:false,arrangement:0,arrangementFrozen:false,mix:0,abChecks:0,mixFrozen:false,masterModules:0,limiting:2,lufs:-14,truePeak:-1,format:"24-bit WAV",levelMatched:false,title:"",cover:false,description:"",metadata:false,copyright:false,deviceChecks:0,backups:0,finalExport:false,published:false,reflection:[],nextGoal:""},
      telemetry:{plays:0,compares:0,interactions:0},...starter
    };
  }

  function mergeDraft(base,draft){
    if(!draft)return base;
    const merged={...base,...draft};
    ["tour","workbench","synth","drums","piano","chords","arrange","record","mix","finish","telemetry"].forEach(key=>merged[key]={...base[key],...(draft[key]||{})});
    return merged;
  }
  const persist=()=>{state.telemetry.interactions++;ProjectStore.saveDraft(state.day,state);onChange(state)};
  const noteName=note=>`${noteNames[note%12]}${Math.floor(note/12)-1}`;
  const synthVersion=()=>({wave:state.synth.wave,pitch:state.synth.pitch,attack:state.synth.attack,release:state.synth.release,brightness:state.synth.brightness,resonance:state.synth.resonance,lfoRate:state.synth.lfoRate,lfoTarget:state.synth.lfoTarget,space:state.synth.space});
  const recallSynthVersion=version=>{if(version)Object.assign(state.synth,version)};
  const synthVersionLabel=version=>version?`${version.wave} · ${noteName(version.pitch)} · B${version.brightness}`:"尚未保存";
  const audition=()=>{const audio=root.querySelector("#studio-preview");if(!audio)return;const result=StudioAudio.play(audio,previewProject());result.promise?.catch(()=>{})};
  function previewProject(){
    const project=JSON.parse(JSON.stringify(state)),emptyDrums={kick:Array(16).fill(0),snare:Array(16).fill(0),hat:Array(16).fill(0),perc:Array(16).fill(0),swing:50};
    if(activity.tool==="synth"){project.drums=emptyDrums;project.arrange={sections:[]};project.mix.channels.forEach(channel=>{channel.mute=false;channel.volume=68;channel.eq=0;channel.comp=0;channel.reverb=0;channel.delay=0})}
    if(activity.tool==="drums"){project.piano={notes:[]};project.chords={sequence:[]};project.arrange={sections:[]}}
    if(activity.tool==="piano"){project.drums=emptyDrums;project.chords={sequence:[]};project.arrange={sections:[]}}
    if(activity.tool==="chords"){project.drums=emptyDrums;project.piano={notes:[]};project.arrange={sections:[]}}
    return project;
  }

  function mount(element,config,draft,callback){root=typeof element==="string"?document.getElementById(element):element;activity=config;activeKit=typeof getDailyKit==="function"?getDailyKit(config.day):null;state=mergeDraft(defaults(config.day,config.starter),draft);state.day=config.day;onChange=callback||(()=>{});render();return state}
  function render(){root.innerHTML=`${transportHtml()}<div class="daw-body"><aside class="daw-track-list">${trackListHtml()}</aside><section class="daw-editor day-mode-${activity.day}">${kitHtml()}${toolHtml()}</section></div>`;bindCommon();bindKit();bindTool()}
  function transportHtml(){return `<div class="daw-transport"><button data-transport="play" title="独奏试听今天的素材">▶</button><button data-transport="stop">■</button><label>BPM <input data-bpm type="number" min="45" max="180" value="${state.bpm}"></label><label>拍号 <select data-timesig><option ${state.timeSig==="4/4"?"selected":""}>4/4</option><option ${state.timeSig==="3/4"?"selected":""}>3/4</option><option ${state.timeSig==="6/8"?"selected":""}>6/8</option></select></label><span class="transport-display">DAY ${String(state.day).padStart(2,"0")} · 今日素材独奏</span><audio id="studio-preview" controls playsinline></audio></div>`}
  function trackListHtml(){const defaults={tour:["运输控制","轨道区","编辑区","混音器","导出"],synth:["Synth 1","Automation","Snapshots"],drums:["Kick","Snare","Hi-hat","Perc"],piano:["Lead MIDI","Bass MIDI","Velocity"],chords:["Chord Track","Top Voice","Bass"],arrange:["Markers","Sections","Energy"],record:["Input","Takes","Comp"],mix:["Drums","Bass","Music","Vocal","FX"],finish:["Checklist","Exports","Release"]}[activity.tool]||["Track 1","Track 2"],items=activeKit?[activeKit.source,...activeKit.assets]:defaults;return `<p>DAY ${String(activity.day).padStart(2,"0")} MATERIALS</p>${items.map((item,index)=>`<div class="track-item ${index===0?"active":""}"><i></i><span>${item}</span></div>`).join("")}`}
  function toolHtml(){if(activity.tool==="tour")return tourHtml();if(activity.tool==="synth")return synthHtml();if(activity.tool==="drums")return drumsHtml();if(activity.tool==="piano")return pianoHtml();if(activity.tool==="chords")return chordsHtml();if(activity.tool==="arrange")return arrangeHtml();if(activity.tool==="record")return recordHtml();if(activity.tool==="mix")return mixHtml();return finishHtml()}

  function kitHtml(){
    if(!activeKit)return "";
    return `<section class="daily-kit variant-${activity.day%4}" data-day="D${String(activity.day).padStart(2,"0")}"><div class="kit-heading"><div><span>DAY ${String(activity.day).padStart(2,"0")} · INTERACTIVE MATERIAL</span><h3>${activeKit.canvas}</h3></div><p>${activeKit.focus}</p></div><div class="material-rack"><strong>${activeKit.source}</strong>${activeKit.assets.map((asset,index)=>`<button data-material="${index}" class="${state.workbench.materials.includes(index)?"loaded":""}"><i>${String(index+1).padStart(2,"0")}</i><span>${asset}</span><small>${state.workbench.materials.includes(index)?"已载入，可继续编辑":"载入真实音乐素材"}</small></button>`).join("")}</div></section>`
  }

  function bindKit(){root.querySelectorAll("[data-material]").forEach(button=>button.addEventListener("click",()=>{const index=Number(button.dataset.material);applyMaterial(index);if(!state.workbench.materials.includes(index))state.workbench.materials.push(index);persist();render()}))}

  function fillPattern(steps,velocity=.7){const lane=Array(16).fill(0);steps.forEach(step=>{if(step<16)lane[step]=velocity});return lane}
  function applyMaterial(index){
    const day=activity.day;
    if(activity.tool==="synth"){
      const presets=[
        {wave:"sine",pitch:60,attack:2,release:5,brightness:2,space:"Room"},
        {wave:day===52?"square":"triangle",pitch:day===58?43:60,attack:day===53?8:4,release:day===53?9:5,brightness:6,space:"Room"},
        {wave:"sawtooth",pitch:day===58?43:67,attack:1,release:2,brightness:9,space:day===59?"Hall":"Room"}
      ];Object.assign(state.synth,presets[index]);if(state.synth.abSlots)state.synth.abSlots.active="LIVE";
    }else if(activity.tool==="drums"){
      const patterns=[
        {kick:[0,8],snare:[4,12],hat:[0,2,4,6,8,10,12,14],perc:[]},
        {kick:[0,4,8,12],snare:[4,12],hat:[2,6,10,14],perc:[7,15]},
        {kick:[0,3,7,10],snare:[4,12,14],hat:[0,2,4,6,8,10,12,14],perc:[5,11,15]}
      ],pattern=patterns[index];
      roles.forEach(role=>state.drums[role]=fillPattern(pattern[role],role==="snare"&&index===2?.35:role==="hat"?.65:.85));
      if(day===3)state.drums.kick=fillPattern(index===0?[0,4]:index===1?[0,4,8]:[0,4,8,12],.85);
      if(day===7)state.drums.kick=fillPattern(index===0?[0]:index===1?[0,4]:[0,4,8],.85);
      if(day===16)state.drums.swing=[50,62,68][index];
      if(day===18)state.drums.style=index===0?"Pop":index===1?"Hip-hop":"House";
    }else if(activity.tool==="piano"){
      const pool=activity.target.allowedPitchClasses||[0,2,4,5,7,9,11],patterns=[[0,1,2,1],[0,2,4,2],[0,1,3,4]],chosen=patterns[index];
      state.piano.notes=chosen.map((degree,step)=>({pitch:60+pool[degree%pool.length],step:step*2,velocity:index===0?.55:index===1?.72:1}));
      if(day===5)state.piano.notes=[{pitch:60,step:0,velocity:.7},{pitch:61,step:3,velocity:.7},{pitch:62,step:6,velocity:.7},{pitch:72,step:10,velocity:.9}].slice(0,index+2);
      if(day===26)state.piano.notes=index===0?[{pitch:67,step:7,velocity:.8}]:index===1?[{pitch:67,step:7,velocity:.8},{pitch:60,step:15,velocity:.8}]:[{pitch:64,step:2,velocity:.7},{pitch:67,step:7,velocity:.8},{pitch:62,step:10,velocity:.7},{pitch:60,step:15,velocity:.8}];
      if(day===66){state.piano.twoVoices=index>0;state.piano.notes=index===0?[{pitch:60,step:0,velocity:.8},{pitch:64,step:4,velocity:.8},{pitch:67,step:8,velocity:.8}]:[{pitch:60,step:0,velocity:.8},{pitch:64,step:4,velocity:.8},{pitch:67,step:8,velocity:.8},{pitch:72,step:0,velocity:.6},{pitch:69,step:4,velocity:.6},{pitch:67,step:8,velocity:.6}]}
    }else if(activity.tool==="chords"){
      const progressions=[['C','F','G','C'],['C','G','Am','F'],['F','Fm','C','C']],ids=progressions[index];state.chords.sequence=ids.map(id=>({id,inversion:index===1?1:0,seventh:index===2&&id!=="C"}));
    }else if(activity.tool==="arrange"){
      const templates=[['前奏','主歌','副歌'],['主歌','预副歌','副歌'],['副歌','桥段','副歌']],names=day===9?[['节奏'],['节奏','低音'],['节奏','低音','旋律']][index]:day===10?[['开始'],['开始','发展'],['开始','发展','收尾']][index]:templates[index];
      state.arrange.sections=names.map((name,i)=>({name,energy:name==="副歌"?8:name==="前奏"?3:4+i*2,bars:name==="前奏"?4:8,variation:index===2&&i===names.length-1}));state.arrange.selected=Math.max(0,state.arrange.sections.length-1);
    }else if(activity.tool==="record"){
      const snapshots=[{gain:25,distance:35,room:8,monitor:45},{gain:55,distance:15,room:3,monitor:50},{gain:82,distance:8,room:6,monitor:80}];Object.assign(state.record,snapshots[index]);state.record.positionTests++;
    }else if(activity.tool==="mix"){
      const scenes=[[58,55,62,78,45],[65,62,58,72,52],[72,64,48,82,38]][index];state.mix.channels.forEach((channel,i)=>{channel.volume=scenes[i];channel.pan=index===0?50:[20,50,80,50,72][i];channel.role=i===3?"Lead":i===4?"Background":"Support"});state.mix.edits++;
    }else if(activity.tool==="finish"){
      if(day===91)state.finish.coreIntent.push(activeKit.assets[index]);
      else if(day===92)state.finish.feedback.push(activeKit.assets[index]);
      else if(day===98){if(index===0)state.finish.title="未命名作品";if(index===1)state.finish.cover=true;if(index===2)state.finish.description="这首作品从一个克制的动机出发，通过逐渐增加的节奏与和声层次，表达从犹豫走向确认的过程。"}
      else if(day===100)state.finish.reflection.push(activeKit.assets[index]);
    }
  }

  function bindCommon(){
    root.querySelector('[data-transport="play"]').addEventListener("click",()=>{state.telemetry.plays++;if(activity.tool==="drums")state.drums.plays++;if(activity.tool==="piano")state.piano.plays++;if(activity.tool==="chords")state.chords.plays++;if(activity.tool==="synth"){state.synth.plays++;if(!state.synth.wavesPlayed.includes(state.synth.wave))state.synth.wavesPlayed.push(state.synth.wave);if(!state.synth.lfoTargetsPlayed.includes(state.synth.lfoTarget))state.synth.lfoTargetsPlayed.push(state.synth.lfoTarget)}if(activity.tool==="mix")state.mix.plays++;persist();const audio=root.querySelector("#studio-preview");const result=StudioAudio.play(audio,previewProject());result.promise?.catch(()=>{root.querySelector(".transport-display").textContent="音频已生成，请点击右侧原生播放器的三角形"})});
    root.querySelector('[data-transport="stop"]').addEventListener("click",()=>StudioAudio.stop());
    root.querySelector("[data-bpm]").addEventListener("change",event=>{state.bpm=Number(event.target.value);persist()});
    root.querySelector("[data-timesig]").addEventListener("change",event=>{state.timeSig=event.target.value;persist()});
  }
  function bindTool(){if(activity.tool==="tour")bindTour();else if(activity.tool==="synth")bindSynth();else if(activity.tool==="drums")bindDrums();else if(activity.tool==="piano")bindPiano();else if(activity.tool==="chords")bindChords();else if(activity.tool==="arrange")bindArrange();else if(activity.tool==="record")bindRecord();else if(activity.tool==="mix")bindMix();else bindFinish()}

  function tourHtml(){const zones=["transport","tracks","editor","mixer","export"],labels=["① 运输控制","② 轨道列表","③ 编辑区域","④ 混音器","⑤ 导出作品"];return `<div class="daw-tour"><h3>DAW 信号与工作流地图</h3><div>${zones.map((zone,index)=>`<button data-zone="${zone}" class="${state.tour.zones.includes(zone)?"visited":""}">${labels[index]}<small>${state.tour.zones.includes(zone)?"已找到 ✓":"点击探索"}</small></button>`).join("")}</div><p data-tour-hint>请按编号依次点击。每个区域都对应真实 DAW 的核心功能。</p></div>`}
  function bindTour(){root.querySelectorAll("[data-zone]").forEach(button=>button.addEventListener("click",()=>{const zone=button.dataset.zone,expected=(activity.target.zones||[])[state.tour.zones.length];if(zone===expected){if(!state.tour.zones.includes(zone))state.tour.zones.push(zone);persist();render()}else root.querySelector("[data-tour-hint]").textContent=`下一步应寻找：${expected||"已完成"}`}))}

  function synthHtml(){
    const s=state.synth,fields={
      1:["wave","pitch","attack","release","brightness"],51:["wave","brightness","space"],52:["wave"],53:["attack","release"],54:["brightness","resonance"],55:["lfoRate","lfoTarget"],56:[],57:["wave","brightness"],58:["pitch","brightness"],59:["space","release"],60:["wave","brightness","space"]
    }[activity.day]||["wave","pitch","attack","release","brightness"],actions={
      1:["compare"],51:["snapshot","compare"],52:["compare"],53:["snapshot","compare"],54:["automation"],55:["compare"],56:["slice","moveSlice","reverse"],57:["snapshot"],58:["smallSpeaker"],59:["snapshot","compare"],60:["snapshot"]
    }[activity.day]||["snapshot","compare"],ab=s.abSlots||{A:null,B:null,active:"LIVE"},compareLabel=!ab.A?"把当前声音保存为 A":!ab.B?"把修改后的声音保存为 B":`切换并试听 ${ab.active==="A"?"B":"A"}`,labels={snapshot:`保存当前版本 (${s.snapshots.length})`,compare:compareLabel,automation:`记录当前亮度点 (${s.automation.length}/2)`,slice:`建立下一切片 (${Math.min(4,s.slices)}/4)`,moveSlice:"把首个切片移到末尾",reverse:s.reverse?"已反向并升调 ✓":"反向并升调",smallSpeaker:s.smallSpeaker?"小音箱监听已开启 ✓":"开启小音箱监听"};
    const control=key=>key==="wave"?`<label>波形选择<select data-synth="wave">${["sine","triangle","square","sawtooth"].map(w=>`<option value="${w}" ${s.wave===w?"selected":""}>${w}</option>`).join("")}</select></label>`:key==="lfoTarget"?`<label>调制目标<select data-synth="lfoTarget"><option value="filter" ${s.lfoTarget==="filter"?"selected":""}>filter</option><option value="volume" ${s.lfoTarget==="volume"?"selected":""}>volume</option><option value="pitch" ${s.lfoTarget==="pitch"?"selected":""}>pitch</option></select></label>`:key==="space"?`<label>空间模型<select data-synth="space"><option value="Room" ${s.space==="Room"?"selected":""}>Room</option><option value="Hall" ${s.space==="Hall"?"selected":""}>Hall</option></select></label>`:`<label>${{pitch:"音高",attack:"起音 Attack",release:"尾音 Release",brightness:"谐波亮度",resonance:"滤波共振",lfoRate:"LFO 速率"}[key]} <output>${key==="pitch"?noteName(s[key]):s[key]}</output><input data-synth="${key}" type="range" min="${key==="pitch"?36:key==="resonance"||key==="lfoRate"?0:1}" max="${key==="pitch"?72:10}" value="${s[key]}"></label>`;
    const special=activity.day===56?`<div class="sample-slicer ${s.reverse?"reversed":""}">${(s.sliceOrder||[1,2,3,4]).map((id,i)=>`<div class="${i<s.slices?"active":""}" style="--slice:${i}"><span>SLICE ${id}</span><i></i></div>`).join("")}</div>`:activity.day===57?`<div class="layer-stack">${["Sub","Body","Attack"].map(layer=>`<button data-layer="${layer}" class="${s.layers.includes(layer)?"active":""}"><strong>${layer}</strong><span>${layer==="Sub"?"重量":layer==="Body"?"身份":"清晰度"}</span></button>`).join("")}</div>`:"";
    const abPanel=actions.includes("compare")?`<div class="ab-panel"><button data-ab-slot="A" class="${ab.active==="A"?"active":""} ${ab.A?"saved":""}"><strong>A</strong><span>${synthVersionLabel(ab.A)}</span></button><button data-ab-slot="B" class="${ab.active==="B"?"active":""} ${ab.B?"saved":""}"><strong>B</strong><span>${synthVersionLabel(ab.B)}</span></button></div>`:"";
    const automationPanel=activity.day===54?`<div class="automation-lane"><span>AUTOMATION · BRIGHTNESS</span><div>${s.automation.length?s.automation.map((point,index)=>`<i style="--point:${Number(point?.value??s.brightness)}" title="点 ${index+1}：${Number(point?.value??s.brightness)}"><b>${Number(point?.value??s.brightness)}</b></i>`).join(""):'<small>先把亮度调暗并记录，再调亮记录第二个点</small>'}</div></div>`:"";
    const snapshots=s.snapshots.length?`<div class="snapshot-strip"><span>可召回版本</span>${s.snapshots.map((snapshot,index)=>`<button data-recall-snapshot="${index}">V${index+1} · ${synthVersionLabel(snapshot)}</button>`).join("")}</div>`:"";
    return `<div class="synth-workbench specific-day-${activity.day}"><div class="oscilloscope"><i class="wave-${s.wave}"></i><span>${noteName(s.pitch)} · ${s.wave} · ${s.space}</span></div>${special}<div class="parameter-grid compact">${fields.map(control).join("")}</div>${automationPanel}<div class="daw-action-row">${actions.map(action=>`<button data-synth-action="${action}" class="${(action==="reverse"&&s.reverse)||(action==="smallSpeaker"&&s.smallSpeaker)?"active":""}">${labels[action]}</button>`).join("")}</div>${abPanel}${snapshots}${activity.day===60?`<div class="palette-freeze"><input data-palette placeholder="为六类音色板命名" value="${s.paletteName}"><span>${s.snapshots.length}/6 个角色音色</span></div>`:""}</div>`
  }
  function bindSynth(){
    root.querySelectorAll("[data-synth]").forEach(control=>{
      const update=()=>{const key=control.dataset.synth;state.synth[key]=control.tagName==="SELECT"?control.value:Number(control.value);if(state.synth.abSlots)state.synth.abSlots.active="LIVE";state.synth.tweaks++;const output=control.closest("label")?.querySelector("output");if(output)output.textContent=key==="pitch"?noteName(state.synth[key]):state.synth[key];const label=root.querySelector(".oscilloscope span");if(label)label.textContent=`${noteName(state.synth.pitch)} · ${state.synth.wave} · ${state.synth.space}`;persist()};
      control.addEventListener("input",update);control.addEventListener("change",()=>{update();const audio=root.querySelector("#studio-preview");const result=StudioAudio.play(audio,previewProject());result.promise?.catch(()=>{})})
    });
    root.querySelectorAll("[data-synth-action]").forEach(button=>button.addEventListener("click",()=>{const action=button.dataset.synthAction,ab=state.synth.abSlots||(state.synth.abSlots={A:null,B:null,active:"LIVE"});if(action==="snapshot")state.synth.snapshots.push(synthVersion());if(action==="compare"){if(!ab.A){ab.A=synthVersion();ab.active="A"}else if(!ab.B){ab.B=synthVersion();ab.active="B";state.synth.compares++;state.telemetry.compares++}else{ab.active=ab.active==="A"?"B":"A";recallSynthVersion(ab[ab.active]);state.synth.compares++;state.telemetry.compares++}}if(action==="automation")state.synth.automation.push({type:"brightness",value:state.synth.brightness});if(action==="slice")state.synth.slices=Math.min(4,state.synth.slices+1);if(action==="moveSlice"){const order=state.synth.sliceOrder||[1,2,3,4];order.push(order.shift());state.synth.sliceOrder=order;state.synth.sliceMoves++}if(action==="reverse"){state.synth.reverse=!state.synth.reverse;state.synth.pitchShift=state.synth.reverse}if(action==="smallSpeaker")state.synth.smallSpeaker=!state.synth.smallSpeaker;persist();render();audition()}));
    root.querySelectorAll("[data-ab-slot]").forEach(button=>button.addEventListener("click",()=>{const slot=button.dataset.abSlot,ab=state.synth.abSlots;if(!ab?.[slot])return;ab.active=slot;recallSynthVersion(ab[slot]);state.synth.compares++;state.telemetry.compares++;persist();render();audition()}));
    root.querySelectorAll("[data-recall-snapshot]").forEach(button=>button.addEventListener("click",()=>{recallSynthVersion(state.synth.snapshots[Number(button.dataset.recallSnapshot)]);persist();render();audition()}));
    root.querySelectorAll("[data-layer]").forEach(button=>button.addEventListener("click",()=>{const layer=button.dataset.layer;state.synth.layers=state.synth.layers.includes(layer)?state.synth.layers.filter(x=>x!==layer):[...state.synth.layers,layer];persist();render();audition()}));
    root.querySelector("[data-palette]")?.addEventListener("change",event=>{state.synth.paletteName=event.target.value;persist()});
  }

  function drumsHtml(){
    const d=state.drums,shownRoles={3:["kick"],7:["kick"],11:roles,12:["kick","snare","hat"],13:["hat"],14:["hat","perc"],15:["kick","snare","perc"],16:["hat"],17:["snare"],18:roles,19:roles,20:roles}[activity.day]||roles,stepCount=activity.day===7?12:16;
    const controls=[];if(targetHas("swing"))controls.push(`<label>Swing 摆幅 <input data-swing type="range" min="50" max="70" value="${d.swing}"><output>${d.swing}%</output></label>`);if(targetHas("style"))controls.push(`<label>鼓机风格<select data-drum-style>${["Pop","Hip-hop","House"].map(style=>`<option ${d.style===style?"selected":""}>${style}</option>`).join("")}</select></label>`);if(targetHas("minCompares"))controls.push('<button data-drum-action="compare">保存并 A/B</button>');if(targetHas("densityVersions"))controls.push(`<button data-drum-action="version">保存密度版本 (${d.densityVersions})</button>`);controls.push('<button data-drum-action="clear">从空白开始</button>');
    const guide=activity.day===14?"点击循环力度：关闭 → 轻 → 中 → 重。让每拍第一格成为重音。":activity.day===15?"带斜纹的是反拍位置，把推动力放到这些格子。":activity.day===17?"浅绿色是 Ghost Note，主 Snare 必须明显更重。":activity.day===16?"拖动 Swing 后松手，会自动播放新的长短比例。":"点击格子写入真实鼓点；粗线是大拍边界。";
    return `<div class="drum-workbench day-drum-${activity.day}"><div class="drum-toolbar">${controls.join("")}</div>${activity.day===16?`<div class="swing-visual" style="--swing:${d.swing}%"><i>1</i><span></span><i>&</i><span></span><i>2</i></div>`:""}<div class="drum-grid roles-${shownRoles.length} steps-${stepCount}" style="--steps:${stepCount}">${shownRoles.map(role=>`<strong>${roleLabels[role]}</strong>${d[role].slice(0,stepCount).map((velocity,step)=>`<button data-drum="${role}" data-step="${step}" data-velocity="${velocity}" class="v${Math.round(velocity*10)} ${step%4===0?"beat":""} ${step%2===1?"offbeat":""}"><small>${step+1}</small></button>`).join("")}`).join("")}</div><p class="grid-help">${guide}</p></div>`
  }
  function bindDrums(){root.querySelectorAll("[data-drum]").forEach(button=>button.addEventListener("click",()=>{const role=button.dataset.drum,step=Number(button.dataset.step),current=state.drums[role][step];state.drums[role][step]=current===0?.35:current<.6?.7:current<1?1:0;persist();render()}));root.querySelector("[data-swing]")?.addEventListener("change",event=>{state.drums.swing=Number(event.target.value);persist();render();const result=StudioAudio.play(root.querySelector("#studio-preview"),state);result.promise?.catch(()=>{})});root.querySelector("[data-drum-style]")?.addEventListener("change",event=>{state.drums.style=event.target.value;persist()});root.querySelectorAll("[data-drum-action]").forEach(button=>button.addEventListener("click",()=>{const action=button.dataset.drumAction;if(action==="compare"){state.drums.compares++;state.telemetry.compares++}if(action==="version")state.drums.densityVersions++;if(action==="clear")roles.forEach(role=>state.drums[role]=Array(16).fill(0));persist();render()}))}

  function pianoHtml(){
    const notes=state.piano.notes,get=(pitch,step)=>notes.find(note=>note.pitch===pitch&&note.step===step),allowed=activity.target.allowedPitchClasses||null,strong=activity.target.strongPitchClasses||null,buttons=[];
    if(targetHas("quantizeUsed"))buttons.push(["quantize","80% 量化"]);if(targetHas("humanizeUsed"))buttons.push(["humanize","保留 Humanize"]);if(targetHas("variationUsed","variationCount","motifRepeat"))buttons.push(["variation",`复制 + 变化 (${state.piano.variationCount})`]);if(targetHas("minCompares"))buttons.push(["compare","A/B 对比"]);if(targetHas("twoVoices"))buttons.push(["twoVoices",state.piano.twoVoices?"双声部已开启":"开启双声部"]);if(targetHas("endFill","fillsInRests"))buttons.push(["endFill","标记段尾 Fill"]);if(targetHas("targetMelody"))buttons.push(["targetMelody","显示旋律目标"]);buttons.push(["clear","清空网格"]);
    const guide=activity.day===5?"素材包含 C4。请亲手加入相邻键、隔一个键和 C5。":activity.day===6?"再次点击已写入音符可切换为重音。":activity.day===26?"左半是问句，右半是答句；第 8、16 格分别是句尾。":activity.day===27?"让中间出现唯一最高点，再把末尾拉回低处。":activity.day===28?"灰色空格也是音乐；至少留下四个休止。":activity.day===29?"带绿色竖线的强拍优先放 C、E、G。":activity.day===66?"用高低两个音区写相反方向，两条线会同时发声。":"点击网格直接写真实 MIDI 音符，再用运输栏播放。";
    return `<div class="piano-workbench day-piano-${activity.day}"><div class="piano-toolbar">${buttons.map(([action,label])=>`<button data-piano-action="${action}">${label}</button>`).join("")}</div><div class="piano-context"><strong>${activeKit.canvas}</strong><span>${guide}</span></div><div class="piano-roll-editor ${activity.day===26?"phrase-halves":""} ${activity.day===66?"two-voice-grid":""}">${pianoPitches.map(pitch=>`<strong class="${[1,3,6,8,10].includes(pitch%12)?"black":""} ${allowed&&!allowed.includes(pitch%12)?"forbidden":""}">${noteName(pitch)}</strong>${Array.from({length:16},(_,step)=>{const note=get(pitch,step),isStrong=step%4===0;return `<button data-pitch="${pitch}" data-piano-step="${step}" class="${note?`note v${Math.round(note.velocity*10)}`:""} ${isStrong?"beat":""} ${strong&&isStrong&&strong.includes(pitch%12)?"target-cell":""} ${allowed&&!allowed.includes(pitch%12)?"forbidden":""}" title="${noteName(pitch)} · 第 ${step+1} 格"></button>`}).join("")}`).join("")}</div><p class="grid-help">${guide}</p></div>`
  }
  function bindPiano(){root.querySelectorAll("[data-pitch]").forEach(button=>button.addEventListener("click",()=>{const pitch=Number(button.dataset.pitch),step=Number(button.dataset.pianoStep),existing=state.piano.notes.find(note=>note.pitch===pitch&&note.step===step);if(!existing)state.piano.notes.push({pitch,step,velocity:.65});else if(existing.velocity<1)existing.velocity=1;else state.piano.notes=state.piano.notes.filter(note=>note!==existing);persist();render()}));root.querySelectorAll("[data-piano-action]").forEach(button=>button.addEventListener("click",()=>{const action=button.dataset.pianoAction;if(action==="quantize")state.piano.quantizeUsed=true;if(action==="humanize")state.piano.humanizeUsed=true;if(action==="variation"){state.piano.variationUsed=true;state.piano.variationCount++}if(action==="compare"){state.piano.compares++;state.telemetry.compares++}if(action==="twoVoices")state.piano.twoVoices=true;if(action==="endFill")state.piano.endFill=true;if(action==="targetMelody")state.piano.targetMelody=true;if(action==="clear")state.piano.notes=[];persist();render()}))}

  function chordsHtml(){
    const c=state.chords,library={31:["C","F","G"],32:["C","Am","F","Dm"],33:["C","Dm","Em","F","G","Am","Bdim"],34:["C","F","G"],35:["C","G","Am","F"],36:["C","Dm","Em","F","G","Am"],37:["C","Dm","F","G","Am"],38:["F","Fm","C"],39:["C","Dm","Em","F","G","Am"],40:chordNames}[activity.day]||chordNames,toolbar=[];
    if(targetHas("inversionsMin"))toolbar.push(`<label>下一和弦转位<select data-inversion><option value="0">原位</option><option value="1" ${c.inversion===1?"selected":""}>第一转位</option><option value="2" ${c.inversion===2?"selected":""}>第二转位</option></select></label>`);if(targetHas("seventhMin"))toolbar.push(`<label><input data-seventh type="checkbox" ${c.seventh?"checked":""}> 下一和弦加七音</label>`);if(targetHas("minCompares"))toolbar.push('<button data-chord-action="compare">保存 A/B 版本</button>');if(targetHas("rhythmChanged"))toolbar.push('<button data-chord-action="rhythm">改变和声节奏</button>');if(targetHas("targetMelody","compatibility"))toolbar.push('<button data-chord-action="target">显示目标长音</button>');toolbar.push('<button data-chord-action="clear">清空进行</button>');
    const targetSlots=activity.target.exact?activity.target.exact:activity.target.containsSequence?activity.target.containsSequence:activity.day===39?["C 长音","E 长音","G 长音","A 长音"]:[];
    return `<div class="chord-workbench day-chords-${activity.day}"><div class="chord-toolbar">${toolbar.join("")}${c.targetMelody?'<span class="target-notes">目标长音：C · E · G · A</span>':""}</div>${targetSlots.length?`<div class="harmony-slots">${targetSlots.map((slot,index)=>`<span><i>${index+1}</i>${slot}</span>`).join("")}</div>`:""}<div class="chord-library">${library.map(name=>`<button data-add-chord="${name}"><strong>${name}</strong><small>${{C:"I",Dm:"ii",Em:"iii",F:"IV",G:"V",Am:"vi",Bdim:"vii°",Fm:"iv 借用",Bb:"♭VII"}[name]}</small></button>`).join("")}</div><div class="chord-timeline">${c.sequence.length?c.sequence.map((item,index)=>`<button data-remove-chord="${index}"><strong>${item.id}${item.seventh?"7":""}</strong><small>${item.inversion?`转位 ${item.inversion}`:"原位"}</small></button>`).join(""):"从素材和弦中选择，亲手搭建从左到右的和声进行"}</div></div>`
  }
  function bindChords(){root.querySelector("[data-inversion]")?.addEventListener("change",event=>{state.chords.inversion=Number(event.target.value);persist();render()});root.querySelector("[data-seventh]")?.addEventListener("change",event=>{state.chords.seventh=event.target.checked;persist();render()});root.querySelectorAll("[data-add-chord]").forEach(button=>button.addEventListener("click",()=>{if(state.chords.sequence.length<12)state.chords.sequence.push({id:button.dataset.addChord,inversion:state.chords.inversion,seventh:state.chords.seventh});persist();render()}));root.querySelectorAll("[data-remove-chord]").forEach(button=>button.addEventListener("click",()=>{state.chords.sequence.splice(Number(button.dataset.removeChord),1);persist();render()}));root.querySelectorAll("[data-chord-action]").forEach(button=>button.addEventListener("click",()=>{const action=button.dataset.chordAction;if(action==="compare"){state.chords.compares++;state.telemetry.compares++}if(action==="rhythm")state.chords.rhythmChanged=true;if(action==="target")state.chords.targetMelody=true;if(action==="clear")state.chords.sequence=[];persist();render()}))}

  function arrangeHtml(){
    const a=state.arrange,selected=a.sections[a.selected],available={9:["节奏","低音","旋律"],10:["开始","发展","收尾"],41:["前奏","主歌","副歌","尾奏"],42:["前奏","主歌"],43:["主歌"],44:["主歌","预副歌","副歌"],45:["主歌","副歌"],46:["副歌","桥段"],47:["副歌"],48:["前奏","主歌","预副歌","副歌","桥段","尾奏"],49:sectionNames,50:["前奏","主歌","预副歌","副歌","桥段","尾奏"],70:["前奏","主歌","预副歌","副歌","桥段","尾奏"]}[activity.day]||sectionNames,actions=[];
    if(targetHas("variation"))actions.push(["variation","把当前段标记为变化版"]);if(targetHas("referenceAnalyzed"))actions.push(["reference","载入并分析参考曲"]);if(targetHas("entryExitMarked"))actions.push(["entryExit","标记进入 / 退出事件"]);if(targetHas("rolesMarked"))actions.push(["roles","标记每段主角"]);if(targetHas("blueprintSaved"))actions.push(["blueprint","冻结并保存蓝图"]);
    return `<div class="arrange-workbench day-arrange-${activity.day}"><div class="arrange-toolbar">${available.map(name=>`<button data-add-section="${name}"><span>＋</span>${name}</button>`).join("")}</div><div class="energy-ruler"><span>LOW</span><i></i><span>ENERGY</span><i></i><span>HIGH</span></div><div class="arrangement-timeline">${a.sections.length?a.sections.map((section,index)=>`<button data-select-section="${index}" class="${a.selected===index?"active":""} ${section.variation?"variation":""}" style="--energy:${section.energy}"><strong>${section.name}</strong><span>${section.bars} 小节</span><i>${section.energy}/10</i></button>`).join(""):"从素材盒载入模板，或用上方段落积木亲手建立时间线"}</div>${selected?`<div class="section-inspector"><strong>正在编辑：${selected.name}</strong><label>能量 <input data-section-energy type="range" min="1" max="10" value="${selected.energy}"><output>${selected.energy}/10</output></label><label>长度 <input data-section-bars type="number" min="2" max="32" value="${selected.bars}"> 小节</label><button data-arrange-action="remove">删除当前段</button></div>`:""}<div class="daw-action-row">${actions.map(([action,label])=>`<button data-arrange-action="${action}">${label}</button>`).join("")}</div></div>`
  }
  function bindArrange(){root.querySelectorAll("[data-add-section]").forEach(button=>button.addEventListener("click",()=>{state.arrange.sections.push({name:button.dataset.addSection,energy:button.dataset.addSection==="副歌"?8:button.dataset.addSection==="前奏"?3:5,bars:8,variation:false});state.arrange.selected=state.arrange.sections.length-1;persist();render()}));root.querySelectorAll("[data-select-section]").forEach(button=>button.addEventListener("click",()=>{state.arrange.selected=Number(button.dataset.selectSection);render()}));root.querySelector("[data-section-energy]")?.addEventListener("change",event=>{state.arrange.sections[state.arrange.selected].energy=Number(event.target.value);persist();render()});root.querySelector("[data-section-bars]")?.addEventListener("change",event=>{state.arrange.sections[state.arrange.selected].bars=Number(event.target.value);persist();render()});root.querySelectorAll("[data-arrange-action]").forEach(button=>button.addEventListener("click",()=>{const action=button.dataset.arrangeAction;if(action==="remove"&&state.arrange.selected>=0){state.arrange.sections.splice(state.arrange.selected,1);state.arrange.selected=-1}if(action==="variation"){state.arrange.variation=true;if(state.arrange.selected>=0)state.arrange.sections[state.arrange.selected].variation=true}if(action==="reference")state.arrange.referenceAnalyzed=true;if(action==="entryExit")state.arrange.entryExitMarked=true;if(action==="roles")state.arrange.rolesMarked=true;if(action==="blueprint")state.arrange.blueprintSaved=true;persist();render()}))}

  function recordHtml(){
    const r=state.record,fields=[],actions=[];
    if(targetHas("gain","safePeak"))fields.push(["gain","输入增益",0,100]);if(targetHas("distance"))fields.push(["distance","麦克风距离 cm",5,60]);if(targetHas("roomMax"))fields.push(["room","房间反射",0,10]);if(targetHas("monitor"))fields.push(["monitor","耳机监听",0,100]);if(targetHas("breathRange"))fields.push(["breath","呼吸保留",0,100]);if(targetHas("timing"))fields.push(["timing","节奏修正量",0,100]);if(targetHas("pitch"))fields.push(["pitch","音高校正量",0,100]);
    if(targetHas("recordTest"))actions.push(["test","录制测试句"]);if(targetHas("takesMin"))actions.push(["take",`录一条完整 Take (${r.takes})`]);if(targetHas("comp"))actions.push(["comp","把选择片段加入 Comp"]);if(targetHas("cleanupMin"))actions.push(["cleanup",`标记并处理噪声 (${r.cleanup})`]);if(targetHas("fades"))actions.push(["fade","加入剪辑淡化"]);if(targetHas("timingEditsMin"))actions.push(["timingEdit",`标记节奏偏差 (${r.timingEdits})`]);if(targetHas("minCompares"))actions.push(["compare","自然版 / 修正版 A/B"]);if(targetHas("snapshotsMin"))actions.push(["snapshot",`保存编辑快照 (${r.snapshots})`]);if(targetHas("keySelected"))actions.push(["key","设置歌曲调性"]);if(targetHas("positionTestsMin"))actions.push(["position",`试听当前麦位 (${r.positionTests})`]);if(targetHas("bestPositionSaved"))actions.push(["best","保存最佳麦位"]);if(targetHas("doubleTracked"))actions.push(["double","录制独立双轨"]);if(targetHas("named"))actions.push(["name","完成轨道命名"]);if(targetHas("groupsMin"))actions.push(["group",`建立分组 (${r.groups})`]);if(targetHas("versioned"))actions.push(["version","保存工程版本号"]);if(targetHas("exportsMin"))actions.push(["export",`导出 Dry / FX (${r.exports})`]);if(targetHas("stemsMin"))actions.push(["stem",`导出一组 Stem (${r.stems})`]);if(targetHas("verified"))actions.push(["verify","在空工程中验证"]);
    return `<div class="record-workbench day-record-${activity.day}"><div class="record-stage"><div class="record-meter"><i style="height:${Math.min(100,r.gain*1.25)}%" class="${r.gain>72?"clip":r.gain>42?"safe":"low"}"></i><span>${r.gain>72?"CLIP":r.gain>42?"SAFE":"LOW"}</span></div><div class="record-visual"><span class="mic">●</span><i style="width:${Math.min(90,r.distance)}%"></i><span class="voice">♫</span><small>${r.distance} cm · Room ${r.room}/10</small></div></div><div class="record-controls focused">${fields.map(([key,label,min,max])=>`<label>${label}<input data-record="${key}" type="range" min="${min}" max="${max}" value="${r[key]}"><output>${r[key]}</output></label>`).join("")}</div><div class="take-waveforms">${Array.from({length:Math.max(1,r.takes)},(_,index)=>`<button data-record-action="comp" class="${r.comp&&index===0?"selected":""}"><strong>TAKE ${index+1}</strong><i style="--seed:${index+1}"></i></button>`).join("")}</div><div class="daw-action-row">${actions.map(([key,label])=>`<button data-record-action="${key}">${label}</button>`).join("")}</div><div class="take-lane">DAY ${activity.day} · TAKES ${r.takes} · COMP ${r.comp?"完成":"未完成"} · SNAPSHOTS ${r.snapshots} · STEMS ${r.stems}</div></div>`
  }
  function bindRecord(){root.querySelectorAll("[data-record]").forEach(control=>control.addEventListener("change",()=>{state.record[control.dataset.record]=Number(control.value);persist();render()}));root.querySelectorAll("[data-record-action]").forEach(button=>button.addEventListener("click",()=>{const a=button.dataset.recordAction,r=state.record;if(a==="test")r.recordTest=true;if(a==="take")r.takes++;if(a==="comp"){r.comp=true;r.compEdits++}if(a==="cleanup")r.cleanup++;if(a==="fade")r.fades=true;if(a==="timingEdit")r.timingEdits++;if(a==="compare")state.telemetry.compares++;if(a==="snapshot")r.snapshots++;if(a==="key")r.keySelected=true;if(a==="position")r.positionTests++;if(a==="best")r.bestPositionSaved=true;if(a==="double")r.doubleTracked=true;if(a==="name")r.named=true;if(a==="group")r.groups++;if(a==="version")r.versioned=true;if(a==="export")r.exports++;if(a==="stem")r.stems++;if(a==="verify")r.verified=true;if(a==="test"||a==="position")r.snapshots++;persist();render()}))}

  function mixHtml(){
    const m=state.mix,channelIndexes={61:[0,1,2,3,4],62:[0,1],63:[1,2,3],64:[2,3,4],65:[0,1,2,3,4],68:[2,3,4],69:[0,1,2,3,4],81:[0,1,2,3,4],82:[0,1,2,3,4],83:[1,2,3],84:[0,1,3],85:[0],86:[2,3,4],87:[3,4],88:[0,1,2,3,4],89:[0,1,2,3,4],90:[0,1,2,3,4]}[activity.day]||[0,1,2,3,4],selected=m.channels[m.selected],showVolume=targetHas("volumeEditsMin","loweredChannelsMin","editsMin"),showPan=targetHas("panSpread","bassCentered"),showMute=targetHas("muteTestsMin","mutedChannelsMin"),showRole=targetHas("leadSelected","roles","roleAssignmentsMin"),pluginKey=targetHas("eqEditsMin","eqReasons")?"eq":targetHas("compressionEditsMin","gainReduction")?"comp":targetHas("transientEditsMin")?"transient":targetHas("reverbTypes","depthOrder")?"reverb":targetHas("delayThrowsMin","delaySynced","clearNextPhrase")?"delay":null,actions=[];
    if(targetHas("minCompares"))actions.push(["compare","A/B 对比"]);if(targetHas("mono"))actions.push(["mono","折叠为单声道"]);if(targetHas("reference"))actions.push(["reference","导入参考曲"]);if(targetHas("levelMatched"))actions.push(["match","匹配响度"]);if(targetHas("quietCheck"))actions.push(["quiet","小音量检查"]);if(targetHas("headroom"))actions.push(["headroom","检查主输出余量"]);if(targetHas("sidechain"))actions.push(["sidechain","创建低频让位"]);if(targetHas("soloPair"))actions.push(["soloPair","Solo Kick + Bass"]);if(targetHas("sectionMixesMin"))actions.push(["section",`保存段落混音 (${m.sectionMixes})`]);if(targetHas("brightnessContrast"))actions.push(["brightness","保存明暗对比"]);if(targetHas("automationTypes"))actions.push(["automationV","画音量曲线"],["automationF","画滤波曲线"],["automationS","画空间曲线"]);if(targetHas("muteTestsMin"))actions.push(["muteTest",`记录 Mute Test (${m.muteTests})`]);if(targetHas("buses"))actions.push(["bus",`创建功能总线 (${m.buses.length}/5)`]);if(targetHas("routingClean"))actions.push(["routing","检查路由"]);if(targetHas("busProcessing"))actions.push(["busFx","轻度处理总线"]);if(targetHas("deviceChecksMin"))actions.push(["device",`切换试听设备 (${m.deviceChecks})`]);if(targetHas("tailChecked"))actions.push(["tail","检查尾音"]);if(targetHas("formats"))actions.push(["wav","打印 WAV"],["mp3","打印 MP3"]);
    const special=activity.day===68?`<div class="automation-lanes">${[["VOLUME",m.automation.includes("volume")],["FILTER",m.automation.includes("filter")],["SPACE",m.automation.includes("space")]].map(([name,done],i)=>`<div class="${done?"done":""}"><strong>${name}</strong><i style="--lane:${i}"></i><span>${done?"已写入":"等待曲线"}</span></div>`).join("")}</div>`:activity.day===88?`<div class="routing-map"><span>TRACKS</span><i>→</i><strong>${m.buses.length||0} BUS</strong><i>→</i><span>MASTER</span></div>`:"";
    return `<div class="mix-workbench day-mix-${activity.day}">${special}<div class="mixer-board channels-${channelIndexes.length}">${channelIndexes.map(index=>{const channel=m.channels[index];return `<div class="channel-strip ${m.selected===index?"selected":""}"><button data-select-channel="${index}">${channel.name}</button>${showVolume?`<label>VOL <output>${channel.volume}</output><input data-channel="volume" data-index="${index}" type="range" min="0" max="100" value="${channel.volume}"></label>`:""}${showPan?`<label>PAN <output>${channel.pan-50}</output><input data-channel="pan" data-index="${index}" type="range" min="0" max="100" value="${channel.pan}"></label>`:""}${showMute?`<button data-channel-mute="${index}" class="${channel.mute?"muted":""}">${channel.mute?"MUTED":"MUTE TEST"}</button>`:""}${showRole?`<select data-role="${index}">${["Lead","Support","Background"].map(role=>`<option ${channel.role===role?"selected":""}>${role}</option>`).join("")}</select>`:""}</div>`}).join("")}</div>${pluginKey?`<div class="plugin-rack focused-plugin"><strong>${selected.name} · ${{eq:"问题 EQ",comp:"峰值压缩",reverb:"空间发送",delay:"Delay Throw",transient:"瞬态塑形"}[pluginKey]}</strong><label>处理量 <output>${selected[pluginKey]}</output><input data-plugin="${pluginKey}" type="range" min="0" max="10" value="${selected[pluginKey]}"></label><span>先选上方轨道，再调整；松手后可用播放键听变化。</span></div>`:""}<div class="daw-action-row">${actions.map(([key,label])=>`<button data-mix-action="${key}" class="${m[key]===true?"active":""}">${label}</button>`).join("")}</div></div>`
  }
  function bindMix(){root.querySelectorAll("[data-select-channel]").forEach(button=>button.addEventListener("click",()=>{state.mix.selected=Number(button.dataset.selectChannel);render()}));root.querySelectorAll("[data-channel]").forEach(control=>control.addEventListener("change",()=>{const channel=state.mix.channels[Number(control.dataset.index)];channel[control.dataset.channel]=Number(control.value);state.mix.edits++;persist();render();const result=StudioAudio.play(root.querySelector("#studio-preview"),state);result.promise?.catch(()=>{})}));root.querySelectorAll("[data-channel-mute]").forEach(button=>button.addEventListener("click",()=>{const channel=state.mix.channels[Number(button.dataset.channelMute)];state.mix.muteTests++;channel.mute=!channel.mute;state.mix.edits++;persist();render()}));root.querySelectorAll("[data-role]").forEach(select=>select.addEventListener("change",()=>{state.mix.channels[Number(select.dataset.role)].role=select.value;state.mix.rolesMarked=true;persist()}));root.querySelectorAll("[data-plugin]").forEach(control=>control.addEventListener("change",()=>{const channel=state.mix.channels[state.mix.selected];channel[control.dataset.plugin]=Number(control.value);state.mix.edits++;persist();render();const result=StudioAudio.play(root.querySelector("#studio-preview"),state);result.promise?.catch(()=>{})}));root.querySelectorAll("[data-mix-action]").forEach(button=>button.addEventListener("click",()=>{const a=button.dataset.mixAction,m=state.mix;if(a==="compare"){m.compares++;state.telemetry.compares++}if(["mono","reference","quietCheck","headroom","sidechain","soloPair","routingClean","busProcessing","tailChecked"].includes(a))m[a]=true;if(a==="match")m.levelMatched=true;if(a==="quiet")m.quietCheck=true;if(a==="section")m.sectionMixes++;if(a==="brightness")m.brightnessContrast=true;if(a.startsWith("automation"))m.automation.push(a==="automationV"?"volume":a==="automationF"?"filter":"space");if(a==="muteTest")m.muteTests++;if(a==="bus"&&!m.buses.includes("Bus"+m.buses.length))m.buses.push("Bus"+m.buses.length);if(a==="routing")m.routingClean=true;if(a==="busFx")m.busProcessing=true;if(a==="device")m.deviceChecks++;if(a==="wav"&&!m.formats.includes("WAV"))m.formats.push("WAV");if(a==="mp3"&&!m.formats.includes("MP3"))m.formats.push("MP3");persist();render()}))}

  function finishHtml(){
    const f=state.finish,button=(action,label)=>`<button data-finish-action="${action}">${label}</button>`;let content="";
    if(activity.day===91)content=`<h4>完成边界</h4><div class="intent-board"><input data-finish-text="intent" placeholder="这首歌必须保留什么？">${button("intent",`加入核心意图 (${f.coreIntent.length}/3)`)}<select data-priority><option>阻塞</option><option>重要</option><option>可选</option></select>${button("priority",`加入问题队列 (${f.priorities.length}/3)`)}<label>冻结日期<input data-freeze-date type="date" value="${f.freezeDate}"></label></div>`;
    if(activity.day===92)content=`<h4>反馈翻译台</h4><div class="feedback-notes"><input data-finish-text="feedback" placeholder="听者的原话或感受">${button("feedback",`添加反馈便签 (${f.feedback.length}/3)`)}${button("layers","拆成感受 / 问题 / 建议")}${button("repeat","标出多人重复问题")}</div>`;
    if(activity.day===93)content=`<h4>结构修订</h4><div class="revision-cards">${button("structure",`删除或调序一次 (${f.structure}/3)`)}${button("structure","缩短一个段落")}${button("structure","移动高潮位置")}${button("freezeStructure",f.structureFrozen?"结构已冻结 ✓":"冻结最终结构")}</div>`;
    if(activity.day===94)content=`<h4>编曲修订</h4><div class="revision-cards">${button("arrangement",`解决声部遮挡 (${f.arrangement}/3)`)}${button("arrangement","删除重复职责")}${button("arrangement","加强段落对比")}${button("freezeArrangement",f.arrangementFrozen?"编曲已冻结 ✓":"冻结最终编曲")}</div>`;
    if(activity.day===95)content=`<h4>混音修订队列</h4><div class="priority-queue">${button("mix",`完成一项修正 (${f.mix}/5)`)}${button("ab",`留下 A/B 证据 (${f.abChecks}/3)`)}${button("freezeMix",f.mixFrozen?"候选 Mix 已冻结 ✓":"冻结候选 Mix")}</div>`;
    if(activity.day===96)content=`<h4>母带链沙盒</h4><div class="master-chain">${Array.from({length:Math.max(1,f.masterModules)},(_,i)=>`<span>MODULE ${i+1}</span>`).join("<i>→</i>")}${button("master",`添加处理模块 (${f.masterModules}/4)`)}<label>Limiter GR <output>${f.limiting} dB</output><input data-finish-range="limiting" type="range" min="0" max="10" value="${f.limiting}"></label>${button("match","与 Pre-master 匹配响度")}</div>`;
    if(activity.day===97)content=`<h4>交付规格</h4><div class="delivery-meters"><label>Integrated LUFS <output>${f.lufs}</output><input data-finish-range="lufs" type="range" min="-20" max="-6" value="${f.lufs}"></label><label>True Peak dBTP <output>${f.truePeak}</output><input data-finish-range="truePeak" type="range" min="-3" max="0" step=".1" value="${f.truePeak}"></label><select data-format><option ${f.format==="24-bit WAV"?"selected":""}>24-bit WAV</option><option>320 kbps MP3</option></select></div>`;
    if(activity.day===98)content=`<h4>作品包装</h4><div class="release-card"><div class="cover-placeholder ${f.cover?"done":""}">${f.cover?"COVER ✓":"COVER"}</div><input data-title placeholder="作品标题" value="${f.title}"><textarea data-description placeholder="用 50–100 字介绍作品">${f.description}</textarea>${button("cover","确认封面方向")}</div>`;
    if(activity.day===99)content=`<h4>发布闸门</h4><div class="release-gates">${button("metadata",f.metadata?"元数据 ✓":"确认作者、标题与日期")}${button("copyright",f.copyright?"版权 ✓":"确认采样与版权")}${button("device",`试听一台设备 (${f.deviceChecks}/3)`)}${button("backup",`建立一份备份 (${f.backups}/2)`)}</div>`;
    if(activity.day===100)content=`<h4>毕业控制台</h4><div class="graduation-console">${button("export",f.finalExport?"最终 WAV 已导出 ✓":"导出最终 WAV")}${button("publish",f.published?"已发布 / 分享 ✓":"标记发布或分享")}<input data-finish-text="reflection" placeholder="写下一项复盘">${button("reflection",`加入毕业复盘 (${f.reflection.length}/3)`)}<input data-goal placeholder="下一首作品的具体目标" value="${f.nextGoal}"></div>`;
    return `<div class="finish-workbench day-finish-${activity.day}"><div class="finish-day-number">${activity.day}</div><div class="finish-column unique">${content}</div></div>`
  }
  function bindFinish(){root.querySelectorAll("[data-finish-range]").forEach(input=>input.addEventListener("change",()=>{state.finish[input.dataset.finishRange]=Number(input.value);persist();render();const result=StudioAudio.play(root.querySelector("#studio-preview"),state);result.promise?.catch(()=>{})}));root.querySelector("[data-format]")?.addEventListener("change",event=>{state.finish.format=event.target.value;persist()});root.querySelector("[data-freeze-date]")?.addEventListener("change",event=>{state.finish.freezeDate=event.target.value;persist()});root.querySelector("[data-title]")?.addEventListener("change",event=>{state.finish.title=event.target.value;persist()});root.querySelector("[data-description]")?.addEventListener("change",event=>{state.finish.description=event.target.value;persist()});root.querySelector("[data-goal]")?.addEventListener("change",event=>{state.finish.nextGoal=event.target.value;persist()});root.querySelectorAll("[data-finish-action]").forEach(button=>button.addEventListener("click",()=>{const a=button.dataset.finishAction,f=state.finish;if(a==="intent"){const v=root.querySelector('[data-finish-text="intent"]')?.value;if(v)f.coreIntent.push(v)}if(a==="feedback"){const v=root.querySelector('[data-finish-text="feedback"]')?.value;if(v)f.feedback.push(v)}if(a==="layers")f.feedbackLayers=true;if(a==="repeat")f.repeatedIssue=true;if(a==="priority")f.priorities.push(root.querySelector("[data-priority]")?.value||"重要");if(a==="structure")f.structure++;if(a==="freezeStructure")f.structureFrozen=true;if(a==="arrangement")f.arrangement++;if(a==="freezeArrangement")f.arrangementFrozen=true;if(a==="mix")f.mix++;if(a==="ab")f.abChecks++;if(a==="freezeMix")f.mixFrozen=true;if(a==="master")f.masterModules++;if(a==="match")f.levelMatched=true;if(a==="cover")f.cover=true;if(a==="metadata")f.metadata=true;if(a==="copyright")f.copyright=true;if(a==="device")f.deviceChecks++;if(a==="backup")f.backups++;if(a==="export")f.finalExport=true;if(a==="publish")f.published=true;if(a==="reflection"){const v=root.querySelector('[data-finish-text="reflection"]')?.value;if(v)f.reflection.push(v)}persist();render()}))}

  function validate(target){
    const errors=[],check=(condition,message)=>{if(!condition)errors.push(message)},allDrums=roles.flatMap(role=>state.drums[role]),hits=allDrums.filter(Boolean).length;
    const values=role=>state.drums[role];const hasAt=(role,steps)=>!steps||steps.every(step=>values(role)[step]>0);
    const notes=[...state.piano.notes].sort((a,b)=>a.step-b.step||a.pitch-b.pitch),pcs=notes.map(note=>note.pitch%12),uniquePcs=[...new Set(pcs)],stepsUsed=[...new Set(notes.map(note=>note.step))];
    const seq=state.chords.sequence,ids=seq.map(item=>item.id),sections=state.arrange.sections,mix=state.mix,record=state.record,finish=state.finish,synth=state.synth;
    const range=notes.length?Math.max(...notes.map(n=>n.pitch))-Math.min(...notes.map(n=>n.pitch)):0;
    const intervals=notes.slice(1).map((note,index)=>Math.abs(note.pitch-notes[index].pitch));
    const includesSequence=(array,sequence)=>sequence?.some?array.join("|").includes(sequence.join("|")):true;
    if(activeKit)check(state.workbench.materials.length>0,"先从今天的素材盒载入至少一个真实音乐素材，再进行编辑");
    if(target.bpm)check(state.bpm>=target.bpm[0]&&state.bpm<=target.bpm[1],`BPM 需要在 ${target.bpm[0]}–${target.bpm[1]}`);if(target.timeSig)check(state.timeSig===target.timeSig,`拍号需要设为 ${target.timeSig}`);
    if(target.zones)check(target.zones.every(zone=>state.tour.zones.includes(zone)),"请按顺序探索全部五个 DAW 区域");
    if(target.minTweaks)check(synth.tweaks>=target.minTweaks,`至少调节 ${target.minTweaks} 个参数`);if(target.minPlays)check(state.telemetry.plays>=target.minPlays||synth.plays>=target.minPlays||state.drums.plays>=target.minPlays||state.piano.plays>=target.minPlays||state.chords.plays>=target.minPlays,`至少完整播放 ${target.minPlays} 次`);if(target.minCompares)check(state.telemetry.compares>=target.minCompares,`至少完成 ${target.minCompares} 次 A/B 对比`);
    if(target.pitchMax)check(synth.pitch<=target.pitchMax,`音高需要低于 ${target.pitchMax}`);if(target.brightness)check(synth.brightness>=target.brightness[0]&&synth.brightness<=target.brightness[1],"亮度不在目标范围");if(target.snapshotsMin)check(synth.snapshots.length>=target.snapshotsMin||record.snapshots>=target.snapshotsMin,`需要保存 ${target.snapshotsMin} 个快照`);if(target.wavesPlayed)check(target.wavesPlayed.every(w=>synth.wavesPlayed.includes(w)),"四种基础波形还没有全部试听");if(target.uniqueWavesMin)check(new Set(synth.snapshots.map(x=>x.wave)).size>=target.uniqueWavesMin,"音色板需要更多不同波形");if(target.envelopeContrast)check(synth.snapshots.length>=2&&Math.abs(synth.snapshots[0].attack-synth.snapshots[1].attack)>=4&&Math.abs(synth.snapshots[0].release-synth.snapshots[1].release)>=4,"两个包络的起音和尾音差异还不够明显");if(target.brightnessSweep){const points=synth.automation.filter(point=>point&&point.type==="brightness").map(point=>Number(point.value));check(points.length>=2&&Math.max(...points)-Math.min(...points)>=4,"请分别记录一个暗点和一个亮点，亮度差至少为 4")};if(target.automationMin)check(synth.automation.filter(point=>point&&point.type==="brightness").length>=target.automationMin,"缺少自动化控制点");if(target.lfoTargets)check(target.lfoTargets.every(value=>synth.lfoTargetsPlayed.includes(value))&&synth.compares>=1,"请分别播放并对比两种 LFO 目标");if(target.slicesMin)check(synth.slices>=target.slicesMin,"切片数量不足");if(target.sliceMovesMin)check(synth.sliceMoves>=target.sliceMovesMin,"请移动至少一个切片");if(target.reverseOrPitch)check(synth.reverse||synth.pitchShift,"请使用一次反向或移调");if(target.layers)check(target.layers.every(x=>synth.layers.includes(x)),"Sub、Body、Attack 三层尚未齐全");if(target.smallSpeakerTest)check(synth.smallSpeaker,"请完成小音箱模式试听");if(target.spaces)check(target.spaces.every(space=>synth.snapshots.some(snapshot=>snapshot.space===space)),"请分别保存 Room 与 Hall 空间快照");if(target.paletteNamed)check(Boolean(synth.paletteName.trim()),"请命名音色板");
    if(target.kickAt)check(hasAt("kick",target.kickAt),"Kick 位置不符合今天目标");if(target.snareAt)check(hasAt("snare",target.snareAt),"Snare 位置不符合今天目标");if(target.hatAt)check(hasAt("hat",target.hatAt),"Hi-hat 位置不完整");if(target.minHits)check(hits>=target.minHits,`鼓点至少需要 ${target.minHits} 个`);if(target.maxHits)check(hits<=target.maxHits,`鼓点不要超过 ${target.maxHits} 个`);if(target.minKick)check(values("kick").filter(Boolean).length>=target.minKick,`Kick 至少 ${target.minKick} 个`);if(target.minSnare)check(values("snare").filter(Boolean).length>=target.minSnare,`Snare 至少 ${target.minSnare} 个`);if(target.minHat)check(values("hat").filter(Boolean).length>=target.minHat,`Hat 至少 ${target.minHat} 个`);if(target.minPerc)check(values("perc").filter(Boolean).length>=target.minPerc,`Perc 至少 ${target.minPerc} 个`);if(target.offbeatMin)check(roles.reduce((sum,r)=>sum+values(r).filter((v,i)=>v&&i%2===1).length,0)>=target.offbeatMin,`反拍至少需要 ${target.offbeatMin} 个`);if(target.accentMin)check(allDrums.filter(v=>v>=1).length>=target.accentMin,"重音数量不足");if(target.ghostMin)check(values("snare").filter(v=>v>0&&v<.6).length>=target.ghostMin,"轻 Snare 幽灵音不足");if(target.swing)check(state.drums.swing>=target.swing[0]&&state.drums.swing<=target.swing[1],`Swing 应在 ${target.swing[0]}–${target.swing[1]}%`);if(target.style)check(state.drums.style===target.style,`风格需要选择 ${target.style}`);if(target.fillMin)check(roles.reduce((sum,r)=>sum+values(r).slice(12).filter(Boolean).length,0)>=target.fillMin,"最后四格的 Fill 不足");if(target.densityVersions)check(state.drums.densityVersions>=target.densityVersions,"请保存三档密度版本");if(target.restsMin&&activity.tool==="drums")check(Array.from({length:16},(_,i)=>roles.every(r=>!values(r)[i])).filter(Boolean).length>=target.restsMin,"鼓组需要更多完整空拍");
    if(target.minNotes)check(notes.length>=target.minNotes,`至少需要 ${target.minNotes} 个音符`);if(target.maxNotes)check(notes.length<=target.maxNotes,`音符不要超过 ${target.maxNotes} 个`);if(target.allowedPitchClasses)check(pcs.every(pc=>target.allowedPitchClasses.includes(pc)),"出现了今天音阶之外的音");if(target.mustPitchClasses)check(target.mustPitchClasses.every(pc=>uniquePcs.includes(pc)),"目标音名还没有找齐");if(target.mustEndPitchClass!==undefined)check(notes.length>0&&notes.at(-1).pitch%12===target.mustEndPitchClass,"最后一个音没有落在目标主音");if(target.intervals)check(target.intervals.every(interval=>intervals.includes(interval)),"半音、全音或八度距离还未全部出现");if(target.velocityVariation)check(new Set(notes.map(n=>n.velocity)).size>=2,"音符力度还没有变化");if(target.quantizeUsed)check(state.piano.quantizeUsed,"请使用量化");if(target.humanizeUsed)check(state.piano.humanizeUsed,"请保留一次 Humanize");if(target.motifRepeat)check(state.piano.variationUsed||notes.some((n,i)=>notes.some(m=>m.step===n.step+4&&m.pitch===n.pitch)),"动机还没有清楚重复");if(target.variationUsed)check(state.piano.variationUsed,"请使用复制 + 变化");if(target.variationCount)check(state.piano.variationCount>=target.variationCount,`至少完成 ${target.variationCount} 次变体`);if(target.questionEnd!==undefined)check(notes.some(n=>n.step===7&&n.pitch%12===target.questionEnd),"问句结尾应停在 G");if(target.answerEnd!==undefined)check(notes.some(n=>n.step===15&&n.pitch%12===target.answerEnd),"答句结尾应回到 C");if(target.minRange)check(range>=target.minRange,`旋律音域至少需要 ${target.minRange} 个半音`);if(target.maxLeap)check(intervals.every(i=>i<=target.maxLeap),"旋律中出现了过大的跳进");if(target.contour==="arch"&&notes.length)check(notes.slice(1,-1).some(n=>n.pitch===Math.max(...notes.map(x=>x.pitch)))&&notes.at(-1).pitch<Math.max(...notes.map(x=>x.pitch)),"旋律还没有形成上升后回落的拱形");if(target.restsMin&&activity.tool==="piano")check(16-stepsUsed.length>=target.restsMin,"旋律留白不足");if(target.endRest)check(!stepsUsed.includes(15),"最后一步需要留白");if(target.strongPitchClasses){const strong=notes.filter(n=>n.step%4===0);check(strong.length&&strong.filter(n=>target.strongPitchClasses.includes(n.pitch%12)).length/strong.length>=target.strongRatio,"强拍和弦音比例不足")};if(target.twoVoices)check(state.piano.twoVoices,"请启用双声部");if(target.contraryMotion)check(state.piano.twoVoices&&range>=5,"反向运动还不够明确");if(target.fillsInRests)check(state.piano.endFill&&16-stepsUsed.length>=target.fillsInRests,"Fill 还没有放在足够的空隙");if(target.endFill)check(state.piano.endFill,"请标记段尾 Fill");
    if(target.minChords)check(seq.length>=target.minChords,`至少需要 ${target.minChords} 个和弦`);if(target.maxChords)check(seq.length<=target.maxChords,`和弦不要超过 ${target.maxChords} 个`);if(target.exact)check(target.exact.every((id,i)=>ids[i]===id),`正确顺序是 ${target.exact.join("–")}`);if(target.mustInclude)check(target.mustInclude.every(id=>ids.includes(id)),"目标和弦还没有全部加入");if(target.diatonicOnly)check(ids.every(id=>["C","Dm","Em","F","G","Am","Bdim"].includes(id)),"出现了 C 大调调外和弦");if(target.majorMin)check(ids.filter(id=>["C","F","G","Bb"].includes(id)).length>=target.majorMin,"缺少大和弦");if(target.minorMin)check(ids.filter(id=>id.includes("m")&&!id.includes("dim")).length>=target.minorMin,"缺少小和弦");if(target.inversionsMin)check(seq.filter(x=>x.inversion>0).length>=target.inversionsMin,"转位和弦数量不足");if(target.seventhMin)check(seq.filter(x=>x.seventh).length>=target.seventhMin,"七和弦数量不足");if(target.containsSequence&&activity.tool==="chords")check(includesSequence(ids,target.containsSequence),`需要包含 ${target.containsSequence.join("→")}`);if(target.borrowedMin)check(ids.filter(id=>["Fm","Bb"].includes(id)).length>=target.borrowedMin,"缺少借用和弦");if(target.rhythmChanged)check(state.chords.rhythmChanged,"请改变一次和声节奏");if(target.targetMelody)check(state.chords.targetMelody,"请启用旋律目标提示");if(target.compatibility){const melody=[0,4,7,9],compatible=seq.slice(0,4).filter((item,index)=>(StudioAudio.chordMidi[item.id]||[]).some(note=>note%12===melody[index])).length;check(state.chords.targetMelody&&seq.length>=4&&compatible/4>=target.compatibility,"四格和弦与 C、E、G、A 目标长音的兼容率还不足 75%")};
    if(target.minSections)check(sections.length>=target.minSections,`至少需要 ${target.minSections} 个段落/声部`);if(target.maxSections)check(sections.length<=target.maxSections,`段落不要超过 ${target.maxSections} 个`);if(target.required)check(target.required.every(name=>sections.some(s=>s.name===name)),`还缺少：${target.required.filter(name=>!sections.some(s=>s.name===name)).join("、")}`);if(target.counts)Object.entries(target.counts).forEach(([name,count])=>check(sections.filter(s=>s.name===name).length>=count,`${name} 至少需要 ${count} 次`));if(target.energyChangesMin)check(sections.slice(1).filter((s,i)=>s.energy!==sections[i].energy).length>=target.energyChangesMin,"能量变化次数不足");if(target.peak){const peaks=sections.filter(s=>s.energy===Math.max(...sections.map(x=>x.energy)));check(peaks.some(s=>s.name===target.peak),`${target.peak} 应成为能量峰值`)}if(target.introMax){const intro=sections.find(s=>s.name==="前奏");check(intro&&intro.energy<=target.introMax,"前奏能量过高")};if(target.maxBarsForIntro){const intro=sections.find(s=>s.name==="前奏");check(intro&&intro.bars<=target.maxBarsForIntro,"前奏太长")};if(target.containsSequence&&activity.tool==="arrange")check(includesSequence(sections.map(s=>s.name),target.containsSequence),`段落顺序需要包含 ${target.containsSequence.join("→")}`);if(target.chorusHigher){const chorus=sections.find(s=>s.name==="副歌"),verse=sections.find(s=>s.name==="主歌");check(chorus&&verse&&chorus.energy>verse.energy,"副歌能量需要高于主歌")};if(target.variation)check(state.arrange.variation,"请标记至少一次变化");if(target.referenceAnalyzed)check(state.arrange.referenceAnalyzed,"请完成参考曲分析");if(target.entryExitMarked)check(state.arrange.entryExitMarked,"请标记一次进入和退出");if(target.blueprintSaved)check(state.arrange.blueprintSaved,"请保存蓝图版本");if(target.rolesMarked)check(state.arrange.rolesMarked||state.mix.rolesMarked,"请标记所有段落主角");if(target.peakValue)check(sections.some(s=>s.energy===target.peakValue),"需要设置一个 10/10 峰值");if(target.hasValley)check(sections.slice(1,-1).some((s,i)=>s.energy<sections[i].energy&&s.energy<sections[i+2].energy),"能量线需要一个清楚低谷");
    if(target.recordTest)check(record.recordTest,"请完成测试录音");if(target.gain)check(record.gain>=target.gain[0]&&record.gain<=target.gain[1],"输入增益不在安全范围");if(target.safePeak)check(record.gain>=42&&record.gain<=68,"峰值未进入 -12 到 -6 dBFS 模拟安全区");if(target.distance)check(record.distance>=target.distance[0]&&record.distance<=target.distance[1],"麦克风距离不在目标范围");if(target.roomMax)check(record.room<=target.roomMax,"房间反射仍过多");if(target.positionTestsMin)check(record.positionTests>=target.positionTestsMin,"麦位测试次数不足");if(target.bestPositionSaved)check(record.bestPositionSaved,"请保存最佳位置");if(target.monitor)check(record.monitor>=target.monitor[0]&&record.monitor<=target.monitor[1],"监听音量不合适");if(target.takesMin)check(record.takes>=target.takesMin,`至少录 ${target.takesMin} 条 Take`);if(target.comp)check(record.comp,"请完成 Comp");if(target.compEditsMin)check(record.compEdits>=target.compEditsMin,"至少完成一次 Comp 编辑");if(target.cleanupMin)check(record.cleanup>=target.cleanupMin,"噪声处理次数不足");if(target.breathRange)check(record.breath>=target.breathRange[0]&&record.breath<=target.breathRange[1],"呼吸处理过少或过度");if(target.fades)check(record.fades,"请加入剪辑淡化");if(target.timingEditsMin)check(record.timingEdits>=target.timingEditsMin,"节奏修正标记不足");if(target.timing)check(record.timing>=target.timing[0]&&record.timing<=target.timing[1],"节奏修正量过度或不足");if(target.pitch)check(record.pitch>=target.pitch[0]&&record.pitch<=target.pitch[1],"音高校正量不在自然范围");if(target.keySelected)check(record.keySelected,"请设置调性");if(target.doubleTracked)check(record.doubleTracked,"请完成独立双轨");if(target.named)check(record.named,"请命名工程");if(target.groupsMin)check(record.groups>=target.groupsMin,"分组数量不足");if(target.versioned)check(record.versioned,"请保存版本号");if(target.exportsMin)check(record.exports>=target.exportsMin,"Dry/FX 导出数量不足");if(target.stemsMin)check(record.stems>=target.stemsMin,"Stem 数量不足");if(target.verified)check(record.verified,"请执行空工程验证");
    const channelEdits=mix.edits,panValues=mix.channels.map(c=>c.pan),muted=mix.channels.filter(c=>c.mute).length;const pluginCount=key=>mix.channels.filter(c=>c[key]>0).length;
    if(target.volumeEditsMin)check(channelEdits>=target.volumeEditsMin,"推子调整次数不足");if(target.editsMin)check(mix.edits>=target.editsMin,`至少需要 ${target.editsMin} 项混音操作`);if(target.headroom)check(mix.headroom,"请执行主输出余量检查");if(target.quietCheck)check(mix.quietCheck,"请完成小音量检查");if(target.bassCentered)check(Math.abs((mix.channels.find(c=>c.name==="Bass")?.pan||50)-50)<=5,"Bass 应保持中心");if(target.panSpread)check(Math.min(...panValues)<35&&Math.max(...panValues)>65,"左右声像展开不足");if(target.mono)check(mix.mono,"请完成单声道检查");if(target.eqEditsMin)check(pluginCount("eq")>=target.eqEditsMin,"使用 EQ 的轨道数量不足");if(target.eqReasons)check(pluginCount("eq")>=3,"请为三处 EQ 问题完成处理");if(target.compressionEditsMin)check(pluginCount("comp")>=1&&mix.edits>=target.compressionEditsMin,"压缩设置还不完整");if(target.levelMatched)check(mix.levelMatched||finish.levelMatched,"请完成响度匹配");if(target.transientEditsMin)check(pluginCount("transient")>=1&&mix.edits>=target.transientEditsMin,"瞬态调整不足");if(target.reverbTypes)check(pluginCount("reverb")>=2,"至少两条轨需要不同空间发送");if(target.delayThrowsMin)check(pluginCount("delay")>=2,"Delay Throw 数量不足");if(target.buses)check(mix.buses.length>=target.buses.length,"功能总线数量不足");if(target.routingClean)check(mix.routingClean,"请完成路由检查");if(target.busProcessing)check(mix.busProcessing,"请处理一个总线");if(target.reference)check(mix.reference,"请导入参考曲");if(target.deviceChecksMin)check((mix.deviceChecks||finish.deviceChecks)>=target.deviceChecksMin,"设备检查次数不足");if(target.formats)check(target.formats.every(format=>mix.formats.includes(format)),"WAV/MP3 导出尚未齐全");if(target.leadSelected)check(mix.channels.some(c=>c.role==="Lead"),"请指定主角轨");if(target.loweredChannelsMin)check(mix.channels.filter(c=>c.volume<60).length>=target.loweredChannelsMin,"需要降低更多竞争声部");if(target.sidechain)check(mix.sidechain,"请设置低频让位");if(target.soloPair)check(mix.soloPair,"请 Solo Kick 与 Bass");if(target.activeChannelsMin)check(mix.channels.filter(c=>!c.mute).length>=target.activeChannelsMin,"活跃声部不足");if(target.roles)check(target.roles.every(role=>mix.channels.some(c=>c.role===role)),"主角、配角和背景角色尚未齐全");if(target.roleAssignmentsMin)check(mix.channels.length>=target.roleAssignmentsMin&&mix.rolesMarked,"请为四条轨分配角色");if(target.automationTypes)check(target.automationTypes.every(a=>mix.automation.includes(a)),"三类自动化尚未齐全");if(target.muteTestsMin)check(mix.muteTests>=target.muteTestsMin,"Mute Test 次数不足");if(target.mutedChannelsMin)check(muted>=target.mutedChannelsMin,"永久静音的低贡献轨不足");if(target.tailChecked)check(mix.tailChecked,"请检查尾音");
    if(target.ascendingCopies){const copies=sections.filter(s=>s.name===target.ascendingCopies);check(copies.length>=2&&copies.every((s,i)=>i===0||s.energy>copies[i-1].energy),`${target.ascendingCopies}的能量需要逐次提升`)}
    if(target.ascendingInto){const index=sections.findIndex(s=>s.name===target.ascendingInto);check(index>0&&sections[index].energy>sections[index-1].energy,"进入目标段落前需要形成能量上升")}
    if(target.finalChorusPeak){const copies=sections.filter(s=>s.name==="副歌");check(copies.length>=2&&copies.at(-1).energy===Math.max(...sections.map(s=>s.energy)),"最终副歌应成为能量峰值")}
    if(target.verseEnergyGapMax){const copies=sections.filter(s=>s.name==="主歌");check(copies.length>=2&&Math.abs(copies[0].energy-copies[1].energy)<=target.verseEnergyGapMax,"两个主歌能量差距过大")}
    if(target.brightnessContrast)check(mix.brightnessContrast,"请保存主歌与副歌的明暗对比");
    if(target.sectionMixesMin)check(mix.sectionMixes>=target.sectionMixesMin,"段落混音版本不足");
    if(target.delaySynced)check(pluginCount("delay")>=1,"请在至少一条轨设置同步 Delay");
    if(target.clearNextPhrase)check(mix.channels.filter(c=>c.delay>0).every(c=>c.delay<=6),"Delay 反馈过长，可能遮住下一句");
    if(target.depthOrder){const values=mix.channels.map(c=>c.reverb).filter(Boolean);check(values.length>=2&&new Set(values).size>=2,"前景与背景的混响发送需要不同")}
    if(target.gainReduction)check(mix.channels.some(c=>c.comp>=target.gainReduction[0]&&c.comp<=target.gainReduction[1]),`压缩量需要在 ${target.gainReduction[0]}–${target.gainReduction[1]} 范围`);
    if(target.coreIntentMin)check(finish.coreIntent.length>=target.coreIntentMin,"核心意图不足三项");if(target.priorityMin)check(finish.priorities.length>=target.priorityMin,"问题优先级分类不足");if(target.freezeDate)check(Boolean(finish.freezeDate)||finish.structureFrozen,"请设置冻结日期或冻结结构");if(target.feedbackMin)check(finish.feedback.length>=target.feedbackMin,"反馈数量不足");if(target.feedbackLayers)check(finish.feedbackLayers,"请完成三层反馈分类");if(target.repeatedIssue)check(finish.repeatedIssue,"请标出重复问题");if(target.structureMin)check(finish.structure>=target.structureMin,"结构修改数量不足");if(target.structureFrozen)check(finish.structureFrozen,"请冻结结构");if(target.arrangementMin)check(finish.arrangement>=target.arrangementMin,"编曲修改数量不足");if(target.arrangementFrozen)check(finish.arrangementFrozen,"请冻结编曲");if(target.mixMin)check(finish.mix>=target.mixMin,"混音修改数量不足");if(target.abChecksMin)check(finish.abChecks>=target.abChecksMin,"A/B 检查不足");if(target.mixFrozen)check(finish.mixFrozen,"请冻结混音");if(target.masterModules)check(finish.masterModules>=target.masterModules[0]&&finish.masterModules<=target.masterModules[1],"母带模块数量不在目标范围");if(target.limitingMax)check(finish.limiting<=target.limitingMax,"限制器增益衰减过多");if(target.lufs)check(finish.lufs>=target.lufs[0]&&finish.lufs<=target.lufs[1],"目标 LUFS 不在合理范围");if(target.truePeakMax)check(finish.truePeak<=target.truePeakMax,"True Peak 需要保留更多余量");if(target.format)check(finish.format===target.format,`导出格式需要选择 ${target.format}`);if(target.title)check(Boolean(finish.title.trim()),"请填写作品标题");if(target.cover)check(finish.cover,"请完成封面");if(target.description)check(finish.description.trim().length>=50,"作品说明至少需要 50 个字");if(target.metadata)check(finish.metadata,"请确认元数据");if(target.copyright)check(finish.copyright,"请确认版权");if(target.backupMin)check(finish.backups>=target.backupMin,"备份数量不足");if(target.finalExport)check(finish.finalExport,"请完成最终导出");if(target.published)check(finish.published,"请标记已发布或已分享");if(target.reflectionMin)check(finish.reflection.length>=target.reflectionMin,"毕业复盘不足三项");if(target.nextGoal)check(Boolean(finish.nextGoal.trim()),"请填写下一首作品目标");
    return {ok:errors.length===0,errors,score:Math.max(0,100-errors.length*12)};
  }

  function getState(){return JSON.parse(JSON.stringify(state))}
  function renderWav(){return StudioAudio.render(state)}
  return {mount,validate,getState,renderWav,render,stop:StudioAudio.stop};
})();
